const PERMISSIONS = {
  WEALTH_BUY_JOURNEY: 'WEALTH_BUY_JOURNEY',
  BUY_MUTUAL_FUND_V2: 'BUY_MUTUAL_FUND_V2',
  MANAGE_MUTUAL_FUNDS: 'MANAGE_MUTUAL_FUNDS',
  INVESTMENT: 'INVESTMENTS',
  SGB: 'SGB',
  RISK_PROFILE: 'RISK_PROFILE',
  INSURANCE: 'INSURANCE',
  OPEN_DEMAT: 'OPEN_DEMAT',
  OPEN_IPO: 'OPEN_IPO',
  INVEST_IPO: 'INVEST_IPO',
  VIEW_TRANSACTIONS: 'VIEW_TRANSACTIONS',
  BUY_MUTUAL_FUNDS: 'BUY_MUTUAL_FUNDS',
  BUY_SGB: 'BUY_SGB',
  OPEN_DEMAT_VENDOR: 'OPEN_DEMAT_VENDOR',
  BUY_SGB_ACTION: 'BUY_SGB_ACTION',
  PIS_DOC: 'PIS_DOC',
};

export default PERMISSIONS;
