export const TRANSACTION_STATUSES = {
  APPROVED: 'APPROVED',
  EDIT_APPROVED: 'EDIT-APPROVED',
  IN_PROGRESS: 'IN-PROGRESS',
  EDIT_IN_PROGRESS: 'EDIT-IN-PROGRESS',
  INITIATED: 'INITIATED',
  EDIT_INITIATED: 'EDIT-INITIATED',
  SYSTEM_REJECTED: 'SYSTEM_REJECTED',
  EDIT_SYSTEM_REJECTED: 'EDIT-SYSTEM_REJECTED',
  SYSTEM_REJECTED_DUE_TO_EXCEEDING_LIMIT: 'SYSTEM_REJECTED_DUE_TO_EXCEEDING_LIMIT',
  EDIT_SYSTEM_REJECTED_DUE_TO_EXCEEDING_LIMIT: 'EDIT-SYSTEM_REJECTED_DUE_TO_EXCEEDING_LIMIT',
  SYSTEM_REJECTED_DUE_TO_APPROVERS_NOT_AVAILABLE: 'SYSTEM_REJECTED_DUE_TO_APPROVERS_NOT_AVAILABLE',
  EDIT_SYSTEM_REJECTED_DUE_TO_APPROVERS_NOT_AVAILABLE: 'EDIT-SYSTEM_REJECTED_DUE_TO_APPROVERS_NOT_AVAILABLE',
  EMPTY_STATUS: '',
  SUCCESS: 'SUCCESS',
  SENT_FOR_APPROVAL: 'SENT_FOR_APPROVAL',
};

export const isSystemRejectedStatus = status => {
  const systemRejectedStatuses = [
    TRANSACTION_STATUSES.SYSTEM_REJECTED,
    TRANSACTION_STATUSES.SYSTEM_REJECTED_DUE_TO_APPROVERS_NOT_AVAILABLE,
    TRANSACTION_STATUSES.SYSTEM_REJECTED_DUE_TO_EXCEEDING_LIMIT,
  ];
  return systemRejectedStatuses.includes(status.toUpperCase());
};

export const isSentForApprovalStatus = status => {
  const sentForApprovalStatuses = [
    TRANSACTION_STATUSES.INITIATED,
    TRANSACTION_STATUSES.IN_PROGRESS,
    TRANSACTION_STATUSES.EDIT_INITIATED,
    TRANSACTION_STATUSES.EDIT_IN_PROGRESS,
  ];
  return sentForApprovalStatuses.includes(status.toUpperCase());
};

export const isSuccessStatus = status => {
  const successStatuses = [
    TRANSACTION_STATUSES.APPROVED,
    TRANSACTION_STATUSES.EDIT_APPROVED,
    TRANSACTION_STATUSES.EMPTY_STATUS,
  ];
  return successStatuses.includes(status.toUpperCase());
};
