import { translate } from 'l10n';

const Errors = {
  ERR_DBC_ACCOUNT_NOT_FOUND: {
    TITLE: translate('ERROR.DEBIT_CARD.ERR_DBC_ACCOUNT_NOT_FOUND.TITLE'),
    DESCRIPTION: translate('ERROR.DEBIT_CARD.ERR_DBC_ACCOUNT_NOT_FOUND.DESCRIPTION'),
  },
  ERR_DBC_CARD_NOT_FOUND: {
    TITLE: translate('ERROR.DEBIT_CARD.ERR_DBC_CARD_NOT_FOUND.TITLE'),
    DESCRIPTION: translate('ERROR.DEBIT_CARD.ERR_DBC_CARD_NOT_FOUND.DESCRIPTION'),
  },
  ERR_CARD_NOT_FOUND: {
    TITLE: translate('ERROR.DEBIT_CARD.ERR_CARD_NOT_FOUND.TITLE'),
    DESCRIPTION: translate('ERROR.DEBIT_CARD.ERR_CARD_NOT_FOUND.DESCRIPTION'),
  },
  ERROR_LINK_DEBIT_CARD: {
    TITLE: translate('ERROR.DEBIT_CARD.ERROR_LINK_DEBIT_CARD.TITLE'),
    DESCRIPTION: translate('ERROR.DEBIT_CARD.ERROR_LINK_DEBIT_CARD.DESCRIPTION'),
  },
  ERR_FETCH_DEBIT_CARD_DETAILS: {
    TITLE: translate('ERROR.DEBIT_CARD.ERR_FETCH_DEBIT_CARD_DETAILS.TITLE'),
    DESCRIPTION: translate('ERROR.DEBIT_CARD.ERR_FETCH_DEBIT_CARD_DETAILS.DESCRIPTION'),
  },
  ERR_FETCH_CARD_DETAILS: {
    TITLE: translate('ERROR.ERROR_FETCH_CARD_DETAILS.TITLE'),
    DESCRIPTION: translate('ERROR.ERROR_FETCH_CARD_DETAILS.DESCRIPTION'),
  },
  ERR_DEFAULT: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_BAD_REQUEST: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_INVALID_THIRD_PARTY_APP: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_USER_NOT_ALLOWED: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_USER_NOT_ONBOARDED: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_INVALID_ID_TOKEN_ERROR: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_SESSION_TRANSFER_FAILED: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_STS_INTERNAL_SERVER_ERROR: {
    TITLE: translate('ERROR.ERR_DEFAULT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_DEFAULT.DESCRIPTION'),
  },
  ERR_ACC_FETCH_ACCOUNT_ERROR: {
    TITLE: translate('ERROR.ERR_ACC_FETCH_ACCOUNT_ERROR.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_ACC_FETCH_ACCOUNT_ERROR.DESCRIPTION'),
  },
  ERR_ACC_CUSTOMER_HAVE_NO_ACCOUNT: {
    TITLE: translate('ERROR.ERR_ACC_CUSTOMER_HAVE_NO_ACCOUNT.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_ACC_CUSTOMER_HAVE_NO_ACCOUNT.DESCRIPTION'),
  },
  ERR_ACC_CUSTOMER_HAVE_NO_LIABILITY_RELATION: {
    TITLE: translate('ERROR.ERR_ACC_CUSTOMER_HAVE_NO_LIABILITY_RELATION.TITLE'),
    DESCRIPTION: translate('ERROR.ERR_ACC_CUSTOMER_HAVE_NO_LIABILITY_RELATION.DESCRIPTION'),
  },
  ERR_DEP_DB_RECORD_FETCHED_FAILED: {
    TITLE: translate('ERROR.FORM15GH.TITLE'),
    DESCRIPTION: translate('ERROR.FORM15GH.DESCRIPTION'),
  },
  ERR_RAS_CUSTOMER_TYPE_NOT_ELIGIBLE: {
    TITLE: translate('ERROR.FORM15GH.TITLE'),
    DESCRIPTION: translate('ERROR.FORM15GH.DESCRIPTION'),
  },
  ERR_RAS_BAD_REQUEST: {
    TITLE: translate('ERROR.FORM15GH.TITLE'),
    DESCRIPTION: translate('ERROR.FORM15GH.DESCRIPTION'),
  },
  ERR_PROFILE_NEW_MOBILE_SAME_AS_ALREADY_REGISTERED_MOBILE_ERROR: {
    TITLE: translate('ERROR.SAME_MOBILE_NUMBER_UPDATE.TITLE'),
    DESCRIPTION: translate('ERROR.SAME_MOBILE_NUMBER_UPDATE.DESCRIPTION'),
  },
  ERR_DUP_MOB_NUM: {
    TITLE: translate('ERROR.MOBILE_NUMBER_ALREADY_REGISTERED.TITLE'),
    DESCRIPTION: translate('ERROR.MOBILE_NUMBER_ALREADY_REGISTERED.DESCRIPTION'),
  },
};

export default Errors;
