import LocalizedStrings from 'react-native-localization';

const ComponentConstants = new LocalizedStrings({
  en: {
    WEALTH: {
      AMOUNT: 'Amount',
      DURATION: {
        ONE_MONTH: '1 month',
        THREE_MONTH: '3 months',
        SIX_MONTH: '6 months',
        ONE_YEAR: '1 year',
        THREE_YEAR: '3 years',
        FIVE_YEAR: '5 years',
      },
      EDIT: 'Edit',
      CHECK_STATUS: 'Check status',
      OK: 'OK',
      CLOSE: 'Close',
      SUCCESS: 'Success',
      REFERENCE_NUMBER: 'Reference number',
      TERMS_AND_CONDITIONS_TITLE: 'Terms & Conditions',
      SORRY_SOMETHING_WENT_WRONG: 'Sorry, something went wrong.',
      DOWNLOAD_SUCCESSFUL: 'Download successful',
      DOWNLOAD_FAILED: 'Download failed',
      EMAIL_SENT_TO_REGISTERED_EMAIL: 'The report is sent to your email address registered with us.',
      ERROR_POPUP: {
        SORRY: 'Sorry',
        ALERT: 'Alert!',
        NOTE: 'Note',
        CHANGE_SIP_DETAILS: 'You have not changed any existing SIP details. Please make change to proceed.',
        COULD_NOT_PROCESS_REQ: 'We could not process your request. Please retry.',
        COULD_NOT_FETCH_MF_MASTER: 'We could not fetch mutual fund details. Please retry.',
        COULD_NOT_VALIDATE_PAN: 'We could not validate your PAN.',
        COULD_NOT_FETCH_DETAILS: 'We could not fetch all details. Please retry.',
        IPV_NOT_DONE_MSG: 'Your IPV is not done yet. Please visit the nearest branch to get it done.',
        KYC_NOT_DONE:
          'Please visit us at a branch near you with your PAN card, address proof, and one photograph to complete your MF KYC',
        REDEEM_SWITCH_NOT_AVAILBLE:
          'You do not have free units for {action}. Please initiate once units are available for {action}.',
        FILE_SIZE_EXCEEDS: 'File size exceeded 2.5MB.',
        FILE_TYPE_NOT_SUPPORTED: 'Please upload file of type jpeg/png/bmp only',
        COULD_NOT_FETCH_TNC: 'Sorry, due to a technical error, we could not process your request. Please retry later.',
        ERR_ZERO_ACCOUNTS:
          'Sorry, your request could not be processed because your account type does not allow this action.',
        ERR_DEBIT_FROZEN: 'Your account(s) is frozen. Please reach our banker on call for details.',
        ERR_BUY_SGB_PAN_UPLOAD: 'Please update your PAN details and retry',
        DEMAT_PAN: 'Please update your PAN details and retry.',
        PROCEED: 'Proceed',
        CANCEL: 'Cancel',
        REGISTER_EMAIL: 'Register email',
        EMAIL_ID_NOT_REGISTERED:
          'Please update your email address via your app and retry as your details are not updated with us.',
      },
      TNC_REDEEM: 'By clicking on redeem I confirm to have read and agreed to the ',
      TNC_STOP_STP: 'By clicking on Stop STP I confirm to have read and agreed to the ',
      TNC_BUY: 'By clicking on buy I confirm to have read and agreed to the ',
      TNC_BUY_SGB: 'By clicking on buy I confirm to have read and agreed to the ',
      TNC_SWITCH: 'By clicking switch I confirm to have read and agreed to the ',
      TNC_EDIT_SIP: 'By clicking on Edit SIP I confirm to have read and agreed to the ',
      TNC_PAUSE_SIP: 'By clicking on pause SIP I confirm to have read and agreed to the ',
      TNC_PAUSE_STOP_SIP: 'By clicking on pause/stop SIP I confirm to have read and agreed to the ',
      TNC_STOP_SWP: 'By clicking on Stop SWP I confirm to have read and agreed to the ',
      TNC_FATCA: 'By submitting, I agree to the ',
      TNC_FATCA_1: ' and authorize IDFC FIRST Bank to share my details with CVL for Mutual fund KYC process.',
      TNC_MF_CARTING: 'By clicking on confirm I agree to have read and agreed to the ',
      TNC: 'Terms and Conditions',
      TNC_IDFC_DEMAT_ACCOUNT_1:
        'I understood and consent to send demographic, bank account details and signature available with IDFC FIRST Bank to NSDL for demat account opening. I hereby agree to ',
      TNC_IDFC_DEMAT_ACCOUNT_2: ', Schedule of Charges',
      TNC_IDFC_DEMAT_ACCOUNT_3:
        ' and acknowledge and declare that I have received, read, understood and agree to the contents of',
      TNC_IDFC_DEMAT_ACCOUNT_4:
        ' Rights and Obligations of Beneficial Owner and Depository Participant as prescribed by SEBI and Depositories.',
      DOWNLOAD_REPORTS: 'Download reports',
      VIEW_INVESTMENT_REPORTS: 'View investment reports',
      DASHBOARD: {
        YOUR_INVESTMENTS: 'Your investments',
        VIEW_DETAILS: 'View details',
        NEW_INVESTMENT_DESCRIPTION:
          'You haven’t invested with us yet. View a list of personalised mutual funds that suit your risk appetite',
        USER_WITH_NO_BUY_PERMISSION_AND_NO_HOLDINGS:
          'Sorry, mutual fund transaction facility is not available to you yet.',
        INVEST_IN_MUTUAL_FUNDS: 'Invest in mutual funds',
        YOUR_RISK_PROFILE: 'Your risk profile',
        MANAGE: 'Manage',
        CHANGE: 'Change',
        ADD_YOUR_RISK_PROFILE: 'Add your risk profile',
        TOP_MUTUAL_FUNDS: 'Top mutual funds',
        START_AN_SIP: 'Start an SIP',
        IDFC_FIRST_DEMAT_ACCOUNT: 'Instant demat account',
        INVEST_INTO_IPO: 'Invest into IPO - ASBA',
        SAVING_GOALS: 'Saving goals',
        SAVE_TAX: 'Save tax',
        TRADING_AND_DEMAT: 'Trading and demat',
        THREE_IN_ONE_ACCOUNT: 'IDFC FIRST 3-in-1 account',
        PORTFOLIO_INVESTMENT_SCHEME: 'Portfolio Investment Scheme',
        TOTAL_INVESTMENT_VALUE: 'Total investment value',
        CURRENT_INVESTMENT_VALUE: 'Current investment value',
        TOTAL_GAIN_LOSS_VALUE: 'Total gain/loss value',
        ABSOLUTE_RETURN: 'Absolute return',
        INV_SUMMARY_API_ERROR_MSG: 'Investment summary currently unavailable',
        ASSET_ALLOCATION: {
          LABEL: 'Asset allocation',
          PIE_CHART_LABEL: 'Investment \nbreakdown',
          ERROR: 'Asset allocation currently unavailable',
        },
        PRODUCT_DISTRIBUTION: {
          LABEL: 'Product distribution',
          ERROR: 'Product distribution currently unavailable',
        },
        ALERTS: {
          SGB_TRANCHE: 'SGB tranche is open until {endDate}. Buy now!',
          FIRST_TRANSACTION: 'View your first mutual fund transactions here',
          SGB_FIRST_TRANSACTION: 'View your first SGB transaction here',
          KYC_PENDING: 'Your KYC is pending! Complete to continue investing.',
        },
      },
      FATCA: {
        FATCA_SUCCESS_MSG: 'Your FATCA form is submitted successfully',
        ARE_YOU_POLITICALLY_EXPOSED: 'Are you politically exposed?',
        FATCA_FORM_LABEL: 'FATCA form',
        ADD_COUNTRY: 'Add country',
        REMOVE: 'Remove',
        INDIA: 'India',
        OTHER: 'Other',
        COUNTRY_OF_TAX_RESIDENCY: 'Country of tax residency',
        SCREEN_DESC: 'Please spare a minute to complete your Mutual fund KYC process',
        ALL_COUNTRIES: 'All countries',
        IDENTIFICATION_TYPE: 'Identification type',
        TAX_PAYER_ID_NUMBER: 'Tax payer identification number',
        ADDRESS_TYPE: 'Address type',
        OCCUPATION: 'Occupation',
        SOURCE_OF_WEALTH: 'Source of wealth',
        GROSS_ANNUAL_INCOME: 'Gross annual income',
        HEADER: 'FATCA declaration',
        TOOLTIP_MSG:
          'According to SEBI, Politically exposed persons (PEP) are individuals or close relatives of such individuals, who are or have been entrusted with prominent public functions in a country. Example Heads of States or of Governments, senior politicians, senior government/judicial/military officers, senior executives of state-owned corporations, important political party officials, etc.',
      },
      RISK_PROFILE: {
        SUBMIT_RISK_PROFILE_BUTTON_ACCESSIBILITY_LABEL: 'Press this button to submit risk profile option',
        CATEGORY_SCREEN_TEXT: 'Select an investment style that best describes you',
        IM_NOT_SURE: 'I’m not sure',
        WELL_HELP_YOU: 'Not sure? We’ll help you',
        INVEST_WITHOUT_RISK_PROFILING: 'Invest without risk profiling',
        DEBT: 'Debt',
        EQUITY: 'Equity',
        YOUR_RISK_PROFILE: 'Your risk profile',
        CHANGE: 'Change',
        INVEST: 'Invest',
        HEADER: 'Risk profile',
      },
      MUTUAL_FUND_BUY: {
        CHOOSE_INVESTMENT_OPTION: 'Please choose an investment plan',
        BUY_SINGLE_MF_HEADER: 'Mutual funds',
        MF_CARTING_PAGE_TITLE: 'Mutual funds',
        MINIMUM_AMOUNT_MESSAGE: 'Please enter a amount greater than or equal to ₹',
        MINIMUM_INVESTMENT_AMOUNT_MESSAGE: 'Minimum investment amount {amount} ',
        MAXIMUM_INVESTMENT_AMOUNT_MESSAGE: 'Maximum investment amount {amount}',
        SIP_STEPUP_HINT: 'Amount should be in multiples of ₹500 (eg.₹1000, ₹1500,… )',
        SIP_STEPUP_ERROR_MESSAGE: 'Please enter amount in multiple of ₹500.',
        MULTIPLE_ERROR_MESSAGE: 'Amount should be in multiples of ₹{multiple}',
        NOT_ENOUGH_AMOUNT_MESSAGE: 'Please select lesser amount than available in the account',
        CHOOSE_INV_ACCOUNT_LABEL: 'Investment account',
        CHOOSE_BANK_ACCOUNT_LABEL: 'Debit bank account',
        MIN_INVESTMENT_AMOUNT_HINT: 'Minimum investment amount ',
        LUMP_SUM_LABEL: 'Lump sum amount',
        SIP_LABEL: 'SIP amount',
        CHANGE_SIP_LABEL: 'Change SIP amount',
        STEP_UP_SIP_LABEL: 'Amount',
        SIP_DATE_LABEL: 'SIP date',
        CHANGE_SIP_DATE: 'Change SIP date',
        SELECT_SIP_DATE: 'Select your SIP date',
        SIP_STEP_UP_MESSAGE: 'Step-up (SIP increase yearly)',
        ADD_SIP_STEP_UP_MESSAGE: 'Add step-up (SIP increase yearly)',
        ADD_STEUP_TOOLTIP:
          'Step-up SIP means that you would like to increase your SIP amount annually. This amount must be in the multiples of ₹500.',
        BUY: 'Buy',
        NEXT: 'Next',
        SIP_TYPE: {
          STEPUP: 'STEPUP',
          PERPETUAL: 'PERPETUAL',
        },
        AMOUNT: 'AMOUNT',
        PROGRESS: 'Progress',
        EDIT: 'Edit',
        DELETE: 'Delete',
        CONFIRM: 'Confirm',
        BALANCE: 'Balance',
        MUTUAL_BUY_SUCCESS_MSG: 'We have received your request to buy a ',
        MUTUAL_SINGLE_BUY_SIP_SUCCESS_MSG:
          'Success! Your investment in SIP {schemeName} of ₹{amount} on {date} of every month is set. Transactions executed will reflect in your portfolio within 3 working days.',
        MUTUAL_SINGLE_BUY_LUMPSUM_SUCCESS_MSG:
          'Success! Your lump sum investment in {schemeName} of ₹{amount} is complete. Transactions executed will reflect in your portfolio within 3 working days.',
        MUTUAL_BUY_SIP_SUCCESS_MSG:
          'Sorry, while your SIP request is successfully processed, your lump sum investment request failed.  Please retry after some time.',
        MUTUAL_BUY_LUMSUM_SUCCESS_MSG:
          'Sorry, while your lump sum investment request is successfully processed, your SIP request failed.  Please retry after some time.',
        MUTUAL_BUY_LUMSUM_SIP_FAIL_MSG:
          'Sorry, due to a technical error, we could not process your SIP and lump sum investment requests. Please retry after some time.',
        PROCEED_BTN: 'Proceed to fund ',
        TOTAL_INVESTMENT_AMOUNT: 'Total investment amount',
        SIP: 'SIP',
        MONTHLY: 'Monthly',
        ONETIME: 'One time',
        ONE_TIME_MONTHLY: 'One time + monthly',
        LUMP_SUM: 'Lump sum',
        LUMP_SUM_PLUS_SIP: 'Lump sum + SIP',
        FUNDS_SELECTED: 'Funds selected',
        INVESTMENTS: 'Investments',
        PAYMENT_DETAILS: 'Payment details',
        HOLDING_PATTERN: 'Holding pattern',
        DEBIT_ACCOUNT_LABEL: 'Debit A/C',
        DEBIT_ACCOUNT_ERROR_MSG: 'You have insufficient funds in the above account. Please choose another account.',
        DELETE_CONFIRMATION_MSG: 'Are you sure you want to delete this fund?',
        CARTING_RESULT_SUCCESS_MSG:
          'Request for the following funds is received. Transactions executed will reflect in your portfolio within 3 working days.',
        CARTING_RESULT_SUCCESS_MSG_KYC_PENDING:
          'Your investment request is received and will be processed subject to successful KYC verification, which may take up to 7 working days. Funds will only be debited from your account after this.',
        CARTING_RESULT_ERROR_MSG:
          'Sorry, we were unable process the request for the following funds. Please try again after sometime.',
        SUCCESSFUL_TRANSACTION: 'Successful transactions',
        UNSUCCESSFUL_TRANSACTION: 'Unsuccessful transactions',
        MUTUAL_FUNDS: 'Mutual funds',
        INVEST_IN_MUTUAL_FUNDS: 'Invest in mutual funds',
        RECOMMENDED: 'Recommended',
        ANNUALISED_RETURNS: 'Annualised historical returns',
        MORNINGSTAR_RATING: 'Morningstar rating',
        SHOWING_EQUITY_FUNDS: 'Showing equity funds',
        SORT_BY: 'Sort by',
        SELECTET_FUNDS_LABEL: 'Selected {number} {fund}',
        SELECT_MULTIPLE_FUNDS: 'Select multiple funds',
        YIELD_TO_MATURITY: 'Yield to maturity (YTM) ',
        MF_LIST_SEARCH_LABEL: 'Search by fund name, asset and sub-asset class',
        MF_LIST_NEW_SEARCH_PLACEHOLDER: 'Search by funds, AMC...',
        FUNDS_LIMIT_ERROR_MSG: 'Only upto 5 funds can be chosen at a time',
        ORDER_NUMBER: 'Order number',
        NO_RESULT_FOUND_ERR_MSG: 'Sorry, no results to show. \nPlease retry with another entry.',
        MUTUAL_FUND_DETAILS: 'Mutual fund details',
        BUY_NOW: 'Buy now',
        NAV: 'NAV',
        YTM: 'YTM',
        YTM_TOOLTIP:
          'Yield to maturity of a debt fund portfolio is the rate of return an investor could expect if all the securities in the portfolio are held until maturity.',
        AUM_SIZE: 'AUM size',
        AS_ON: 'as on',
        FILTERS: 'Filters',
        ASSET_CLASS: 'Asset class',
        ALL_FUNDS: 'All funds',
        AMC: 'AMC',
        SHOW_RESULTS: 'Show results',
        RESET_FILTERS: 'Reset filters',
        ASSET_CLASS_ERR_MSG: 'Please select at least one asset class or AMC',
        ALL_AMC: 'All AMCs',
        AMCS_NOT_AVAILABLE: 'AMC filters not available.',
        ASSET_CLASS_NOT_AVAILABLE: 'Asset class filters not available.',
        NO_SEARCH_RESULT: 'We were unable to find any results....',
        MF_LIST_SEARCH_PLACEHOLDER: 'Enter keywords',
        FUND_RISKOMETER: 'Fund riskometer',
        FUND_RISK_PROFILE: 'This is a {risk} fund',
        FUND_RISK_PROFILE_NAME: 'Your current risk profile is ’{risk}’,',
        FUND_RISK_PROFILE_PREFER: '(You prefer {riskDescription})',
        FUND_PERFORMANCE_COMPARED_TO: 'Fund historical performance compared to',
        CATEGORY_AVERAGE: 'Category average',
        BENCHMARK: 'Benchmark',
        WHY_IS_THIS_FUND: 'Why is this a top pick?',
        FUND: 'Fund',
        CATEGORY_AVG: 'Category avg',
        RETURNS: 'Historical returns',
        ABSOLUTE: 'Absolute',
        ANNUALISED: 'Annualised',
        MINIMUM_INVESTMENT: 'Minimum investment',
        EXPENSE_RATIO: 'Expense ratio',
        LOCK_IN_PERIOD: 'Lock in period',
        EXIT_LOAD: 'Exit load',
        MODIFIED_DURATION: 'Modified duration',
        EXPENSE_RATIO_POPOVER_TEXT: 'Annual fee that fund house charges for managing the scheme.',
        LOCK_IN_PERIOD_POPOVER_TEXT:
          ' It’s the period for which investment are locked-in and not available for redemption from investment date.',
        EXIT_LOAD_POPOVER_TEXT:
          'It is the fee that Fund House charge for exiting or redeeming fund before the exit load period.',
        MODIFIED_DURATION_POPOVER_TEXT:
          'Modified Duration is the change in the value of a debt security in response to the change in interest rates.',
        SCHEME_DOCUMENT: 'Scheme document',
        VIEW: 'View',
        RISK: 'risk',
        MATURITY_AMOUNT: 'Maturity Amount',
        INTEREST_RATE: 'Interest Rate',
        MATURITY_DATE: 'Maturity date',
      },
      MUTUAL_FUND_TRANSACTIONS: {
        STATUS_TYPE: 'Status type',
        DATE_RANGE: 'Range',
        ALL_ORDERS: 'All orders',
        ORDER_DATE: 'Order date',
        ORDER_NUMBER: 'Order no',
        FUND_NAME: 'Fund name',
        INVESTMENT_AMOUNT: 'Investment amount',
        STATUS_LABEL: 'Status',
        TRANSACTION_TYPE: 'Transaction type',
        TRACK_ACTION: 'Track',
        REQUEST_RECEIVED: 'Request received',
        ORDER_SUCCESSFUL: 'Order successful',
        ORDER_REJECTED: 'Order rejected',
        REQUEST_EXPIRED: 'Request expired',
        PAYMENT_FAILED: 'Payment failed',
        DATE_LABEL: 'Date',
        TRACK_MUTUAL_FUNDS: 'Track mutual funds',
        TRANSACTION_STATUS: 'Transaction status',
        REPEAT_INVESTMENT: 'Repeat investment',
        UNITS: 'Units',
        STATUS_VALIDATION_MESSAGE: 'Please select at least one type of status',
        NO_TRANSACTIONS_FOUND: 'No transactions found',
        FROM_DATE_LABEL: 'From',
        TO_DATE_LABEL: 'To',
        LAST_MONTH_LABEL: 'Last month',
        CURRENT_MONTH_LABEL: 'Current month',
        LAST_12_MONTHS_LABEL: 'Last 12 months',
        CURRENT_YEAR_LABEL: 'Current year',
        CHOOSE_FROM_CALENDAR_LABEL: 'Choose from calendar',
        KYC_PENDING: 'KYC pending',
        COMPLETE_KYC: 'Complete KYC',
      },
      MUTUAL_FUND_HOLDINGS: {
        YOUR_PORTFOLIO: 'Your portfolio',
        MF_HOLDING_API_FAIL: 'Mutual fund holdings currently unavailable',
        MF_HOLDING_PORTFOLIO_API_FAIL: 'Mutual fund holdings portfolio summary currently unavailable',
        MF_HOLDING_EMPTY_RESPONSE: 'Sorry, no mutual fund for selected criteria!',
        INVESTMENT_VALUE: 'Investment value',
        CURRENT_VALUE: 'Current value',
        MATURITY_AMOUNT: 'Maturity amount',
        INT_RATE: 'Interest rate',
        XIRR: 'XIRR',
        DOWNLOAD_REPORTS: 'Download reports',
        ALL_FUNDS: 'All funds',
        INVESTED_VALUE: 'Invested value',
        GAINORLOSS: 'Gain/Loss',
        MONTHLY_INVESTMENT: 'Monthly investment',
        REDEEM: 'Redeem',
        SWITCH: 'Switch',
        VIEW_FUND_DETAILS: 'View fund details',
        INVEST_MORE: 'Invest more',
        MF_HOLDING_CURRENT_ASSET_API_FAIL: 'Internal server error',
        FUND_FILTER_VALIDATION_MESSAGE: 'Please select at least one fund type',
        CURRENT_ASSET_ALLOCATION: 'Current asset allocation',
        RECOMMENDED_ASSET_ALLOCATION: 'Recommended asset allocation',
        ALL_API_FAIL_MSG: 'Sorry! Something went wrong at the moment\nPlease try again in some time.',
        NO_MUTUAL_HOLDINGS_AVAILABLE: 'You don’t have any mutual fund holdings!',
        INVEST_FUNDS_MSG: 'Invest your money in top performing funds now!',
        ALERT: 'Alert',
        NO_HOLDINGS_ERROR_MESSAGE: 'There are no holdings in your portfolio for the selected asset class.',
      },
      MUTUAL_FUND_DETAILS: {
        FUND_RISKS: {
          LOW: 'Low',
          LOW_TO_MODERATE: 'Low to moderate',
          MODERATE: 'Moderate',
          MODERATELY_HIGH: 'Moderately high',
          HIGH: 'High',
          VERY_HIGH: 'Very high',
        },
      },
      DEBT: 'Debt',
      EQUITY: 'Equity',
      HYBRID: 'Hybrid',
      OTHERS: 'Others',
      PORTFOLIO: 'Portfolio',
      CAPITAL_GAIN: 'Capital gain',
      TRANSACTION: 'Transaction',
      FINANCIAL_YEAR: 'Financial year',
      EXPECTED_SETTLEMENT_DATE: 'Expected settlement date',
      MUTUAL_FUND_HOLDING_PATTERN: {
        HOLDING_PATTERN: 'Holding pattern',
        MF_HOLDING_PATTERN_API_FAIL: 'Current asset allocation currently unavailable!',
        CREDIT_PROFILE_MESSAGE: 'The credit profile indicates the quality of papers held by the fund',
        ASSET_ALLOCATION: 'Asset allocation',
        VIEW_MORE: 'View more',
        VIEW_LESS: 'View less',
        SECTOR: 'Sector',
        COMPANIES: 'Companies',
        MARKET_CAP: 'Market cap',
        CREDIT_PROFILE: 'Credit profile',
        BREAKDOWN: 'Breakdown',
        STOCKS: 'Stocks',
        BONDS: 'Bonds',
      },
      KYC: {
        PAN_VALIDATION_MSG: 'Please enter a valid PAN number.',
        PAN_ATTEMPTS_LEFT: 'You are left with {number} attempts.',
        POP_UP_HEADER: 'Sorry',
        PERMISSION_BLOCKED_DESCRIPTION: 'Please add permission for {permission} from settings.',
        ATTEMPTS_EXHAUSTED_MSG: {
          LINE_1: 'Your PAN details have been submitted incorrectly 5 times.',
          LINE_2:
            'To complete your MF KYC process, please visit an IDFC FIRST Bank branch near you with your PAN card, address proof and MF KYC form.',
        },
        LOCATE_BRANCH: 'Locate branch',
        PAN_ATTEMPT_LEFT: 'You are left with {number} attempt.',
        UPLOAD_PAN_SCREEN_TEXT: 'Please upload or take a picture of your PAN card.',
        COUNTRY_LABEL: 'Country',
        UPLOAD: 'Upload',
        OR: 'OR',
        SKIP: 'Skip',
        TAKE_A_PICTURE: 'Take a picture',
        SELECT_COUNTRY_HEADING: 'Select the country',
        COUNTRY_NAME_LABEL: 'Country name',
        COUNTRY_NAME_MANDATORY_MESSAGE: 'Country name is needed',
        PAN_DETAILS_HEADER: 'PAN details',
        PAN_DETAILS_LABEL: 'Please enter your PAN card number',
        PAN_NUMBER_LABEL: 'PAN number',
        VERIFY: 'Verify',
        PAN_UPLOAD_SUCCESS_MSG: 'PAN uploaded and validated successfully, your KYC is now in process',
      },
      SWITCH: {
        AMOUNT: 'Amount',
        SWITCH: 'Switch',
        HEADER: 'Switch',
        SWITCH_ACTION: 'switch',
        PARTIAL: 'Partial',
        FULL: 'Full',
        STP: 'Systematic transfer',
        SWITCH_BY: 'Switch by',
        MONTHLY_STP_AMOUNT_LABEL: 'Monthly STP amount',
        STP_PLAN_LABEL: 'Systematic transfer plan (STP)',
        START_DATE_LABEL: 'Start date',
        END_DATE_LABEL: 'End date',
        CURRENT_VALUE: 'Current value',
        CHANGE_BUTTON_LABEL: 'Change',
        AVAILABLE_UNITS_TO_SWITCH: 'Available units to switch',
        UNITS: 'Units',
        SWITCH_TYPE: 'Switch type',
        SWITCH_LABEL: 'Switch',
        UNTIL_STOPPED: 'Until stopped',
        UNTIL_STOPPED_HINT: 'Your systematic transfer will continue until you choose to stop it.',
        CHOOSE_A_DAY: 'Choose a date',
        MIN_SWITCH_UNIT: 'Minimum units to switch {units}',
        MAX_SWITCH_UNIT: 'Maximum units to switch {units}',
        UNITS_MULTIPLE_ERROR_MESSAGE: 'Units should be in multiples of {multiple}',
        MIN_SWITCH_AMOUNT: 'Minimum amount to switch {amount}',
        MAX_SWITCH_AMOUNT: 'Maximum amount to switch {amount}',
        AMOUNT_MULTIPLE_ERROR_MESSAGE: 'Amount should be in multiples of ₹{multiple}',
        WHAT_IS_STP: 'What is systematic transfer plan (STP) ?',
        WHAT_IS_STP_HINT:
          'You can periodically transfer a certain amount from one scheme and invest it in another of the same fund house.',
        STP_HEADER: 'Select your STP date',
        SWITCH_DAY_LABEL: 'Start date',
        END_DATE: 'End date',
        SYSTEMATIC_TRANSFER_PLAN: 'Systematic transfer plan',
        CHECK_YOUR_EXIT_AND_TAX: 'Check your exit load and tax implication',
        END_DATE_VALIDATION: 'End date should be greater than start date i.e',
        SWITCH_CONFIRMATION_MSG: 'Are you sure you want to switch?',
        STOP_STP_SUCCESS_MSG:
          'Success! Your request to stop systematic transfer plan from {schemeName1} to {schemeName2} of ₹{amount} is processed.',
        DISCLAIMER:
          'I/We hereby agree & authorize the Bank to switch out my/our Mutual Fund on a first in-first out basis in the selected scheme across holding pattern. \nPlease note: Final units will depend on NAV applicable at the time of request (as confirmed by the AMC)',
        SWITCH_MF_SUCCESS_MSG: 'We have received your request to switch Axis Blue Chip Fund to ',
        TAX_IMPLICATION_HINT: 'Long Term or Short Term Gains tax applicable on switch of your funds.',
        EXIT_LOAD_HINT: 'Exit load charges applicable on your switch amount, if any.',
        PARTIAL_AMOUNT_SWITCH_MF_SUCCESS_MSG:
          'Success! Your partial switch request from {schemeName1} to {schemeName2} of ₹{amount} is processed.',
        PARTIAL_UNITS_SWITCH_MF_SUCCESS_MSG:
          'Success! Your partial switch request from {schemeName1} to {schemeName2} for {noOfUnits} units is processed.',
        FULL_SWITCH_MF_SUCCESS_MSG:
          'Success! Your full switch request from {schemeName1} to {schemeName2} of ₹{amount} is processed.',
        STP_SWITCH_MF_SUCCESS_MSG:
          'Success! Your request for systematic transfer plan from {schemeName1} to {schemeName2} of ₹{amount} is processed.',
      },
      REDEEM: {
        REDEEM_BY: 'Redeem by',
        REDEEM_TYPE: 'Redemption type',
        PARTIAL: 'Partial',
        FULL: 'Full',
        SWP: 'Systematic withdrawal',
        WHAT_IS_SWP: 'What is systematic withdrawal plan (SWP) ?',
        WHAT_IS_SWP_HINT:
          'You can withdraw a pre-determined amount at pre-decided intervals from investments in select schemes.',
        UNTIL_DATE_HINT: 'Your systematic withdrawal will continue until you choose to stop it.',
        SYSTEMATIC_WITHDRAWAL_PLAN: 'Systematic withdrawal plan',
        AMOUNT_LABEL: 'Monthly withdrawal amount',
        MIN_REDEEM_AMOUNT1: 'Minimum redemption amount ',
        MAX_REDEEM_AMOUNT1: 'Maximum redemption amount ',
        MIN_REDEEM_UNIT: 'Minimum redemption unit {units}',
        MAX_REDEEM_UNIT: 'Maximum redemption unit {units}',
        MIN_REDEEM_AMOUNT: 'Minimum redemption amount {amount}',
        MAX_REDEEM_AMOUNT: 'Maximum redemption amount {amount}',
        AMOUNT_MULTIPLE_ERROR_MESSAGE: 'Amount should be in multiples of ₹{multiple}',
        UNITS_MULTIPLE_ERROR_MESSAGE: 'Units should be in multiples of {multiple}',
        START_DATE_LABEL: 'Withdrawal start date',
        SWP_HEADER: 'Select your SWP day',
        END_DATE: 'Withdrawal end date',
        REDEEM_SCREEN_HEADER: 'Redeem',
        REDEEM: 'Redeem',
        REDEMPTION: 'redemption',
        UNIT: 'Units',
        AMOUNT: 'Amount',
        TOTAL_INV_LABEL: 'Total investment',
        CURRENT_VAL_LABEL: 'Current value',
        ABSOLUTE_RETURN_LABEL: 'Absolute return',
        TOTAL_UNIT_LABEL: 'Total units',
        XIRR: 'XIRR',
        EXIT_LOAD: 'Exit load',
        EXIT_LOAD_HINT: 'Exit load charges applicable on your redemption amount, if any.',
        TAX_IMPLICATION: 'Tax implication',
        TAX_IMPLICATION_HINT: 'Long Term or Short Term Gains tax applicable on redemption of your funds.',
        REDEEEM_CONFIRMATION_MSG: 'Are you sure you want to redeem?',
        DISCLAIMER:
          'I/We hereby agree & authorize the Bank to redeem my/our Mutual Fund on a first in-first out basis in the selected scheme across holding pattern. \nPlease note: Final units will depend on NAV applicable at the time of redemption request (as confirmed by the AMC)',
        PARTIAL_AMOUNT_REDEEM_SUCCESS_MSG:
          'Success! Your partial redemption request from {schemeName} of ₹{amount} is processed.',
        PARTIAL_UNITS_REDEEM_SUCCESS_MSG:
          'Success! Your partial redemption request from {schemeName} of {noOfUnits} units is processed.',
        FULL_REDEEM_SUCCESS_MSG: 'Success! Your full redemption request from {schemeName} of ₹{amount} is processed.',
        SWP_REDEEM_SUCCESS_MSG:
          'Success! Your request for systematic withdrawal plan from {schemeName} of ₹{amount} is processed.',
      },
      STOP_STP: {
        HEADER: 'Stop systematic transfer',
        STOP_STP: 'Stop STP',
      },
      STOP_SWP: {
        HEADER: 'Stop systematic withdrawal',
        SYSTEMATIC_WITHDRAWAL_PLAN_SWP: 'Systematic withdrawal plan (SWP)',
        MONTHLY_SWP_AMOUNT: 'Monthly SWP amount',
        STOP_SWP: 'Stop SWP',
        SUCCESS_MSG:
          'Success! Your request to stop systematic withdrawal plan from {schemeName} of ₹{amount} is processed.',
      },
      SIP: {
        RESUME_HEADER: 'Resume SIP',
        MONTHLY_SIP: 'Monthly SIP',
        ADD_SIP_STEP_UP_MESSAGE: 'Add step-up (SIP increase yearly)',
        CHANGE_SIP_STEP_UP_MESSAGE: 'Change step-up amount',
        NTH_OF_EVERY_MONTH: ' of every month',
        STEP_UP_POPOVER_TEXT: 'Stepup popover text',
        NEXT_SIP_DATE: 'Next SIP date',
        TOTAL_INV_LABEL: 'Total Investment',
        CURRENT_VAL_LABEL: 'Current value',
        ABSOLUTE_RETURN_LABEL: 'Absolute return',
        TOTAL_UNIT_LABEL: 'Total units',
        XIRR: 'XIRR',
        ANNUAL_STEP_UP: 'Annual step-up',
        MANAGE_SIP: 'Manage SIP',
        EDIT_SIP: 'Edit SIP',
        PAUSE_SIP: 'Pause SIP',
        PAUSE_AND_STOP_SIP: 'Pause/Stop SIP',
        PAUSE_Or_STOP_SIP_FOR_LABEL: 'Pause/Stop SIP for',
        PAUSE_SIP_FOR_LABEL: 'Pause SIP for',
        SIP_CONFIRMATION_MSG: 'Are you sure you want to pause SIP?',
        STOP_SIP_CONFIRMATION_MSG: 'Are you sure you want to stop SIP?',
        PAUSE_SIP_NOTE: 'Please note: You can pause maximum of 3 consecutive installments without turning it inactive.',
        ERR_MSG_FIRST_ORDER_NOT_EXECUTED:
          'Sorry, your request can only be processed after the first installment of your systematic plan is executed. Please retry after your first installment is complete.',
        START_NEW_SIP: 'Start new SIP',
        PAUSE_SIP_SUCCESS_MSG: 'Success! Your request to pause SIP in {schemeName} is processed.',
        PAUSE_STOP_SIP_SUCCESS_MSG: 'Success! Your request to stop SIP in {schemeName} is processed.',
        EDIT_SIP_SUCCESS_MSG: 'Success! Your requested changes to {schemeName} is processed.',
        REVISED_SIP_AMOUNT: 'Revised SIP amount',
        REVISED_SIP_DATE: 'Revised SIP date',
        REVISED_SIP_STEP_UP_AMOUNT: 'Revised SIP step-up amount',
        RESUME_SIP_DURATION: 'SIP paused for',
        SIP_PAUSED_START_DATE: 'SIP paused on',
        SIP_PAUSED_END_DATE: 'SIP paused until',
        RESUME_SIP_MSG: 'Success! Your request to resume SIP in {schemeName} is processed.',
        UNTIL_RESUMED: 'Until resumed',
        STOP_SIP: 'Stop SIP',
        ONE_MONTH: '1 month',
        TWO_MONTH: '2 months',
        THREE_MONTH: '3 months',
      },
      SYSTEMATIC_PLANS: {
        DOWNLOAD_REPORT: 'Download report',
        SORT_BY: 'Sort by',
        NO_ACTIVE_SIP_MESSAGE: 'You don’t have an active SIP yet! ',
        ACTIVE_SYSTEMATIC_PLANS: 'Your active systematic plans',
        STP: {
          ORDER_NUMBER: 'Order no',
          STOP: 'Stop',
          START_DATE_LABEL: 'Start date',
          STATUS_LABEL: 'Status',
          FUND_FROM: 'Fund STP from',
          FUND_TO: 'Fund STP to',
          TRANSFER_AMOUNT: 'Transfer amount',
          END_DATE: 'End date',
          ORDER_DATE: 'Order date',
        },
        SWP: {
          ORDER_NUMBER: 'Order no',
          STOP: 'Stop',
          START_DATE_LABEL: 'Start date',
          STATUS_LABEL: 'Status',
          WITHDRAWAL_AMOUNT: 'Withdrawal amount',
          END_DATE: 'End date',
          ORDER_DATE: 'Order date',
          FUND_NAME: 'Fund name',
        },
        SIP: {
          ORDER_NUMBER: 'Order no',
          START_DATE_LABEL: 'Start date',
          STATUS_LABEL: 'Status',
          INVESTMENT_AMOUNT: 'Investment amount',
          FUND_NAME: 'Fund name',
          MANAGE: 'Manage',
          RESUME: 'Resume',
          START_AN_SIP: 'Start an SIP',
          INVEST_IN_SIP: 'Invest in SIP and generate wealth in a smarter way',
          SIP_DATE: 'SIP date',
        },
        STATUS: {
          ACTIVE: 'Active',
          IN_ACTIVE: 'Inactive',
          PAUSED: 'Paused',
          CURRENTLY_SKIPPED: 'Currently skipped',
        },
      },
      SGB: {
        SOVEREIGN_GOLD_BOND: 'Sovereign gold bond',
        BUYING_PRICE: 'Buying price',
        DEMAT_ACCOUNT: 'Demat A/C',
        OPTIONAL: 'Optional',
        QUANTITY: 'Quantity in grams',
        QUANTITY_VALIDATION_MESSAGE: 'Quantity should be between 1 and 4000',
        QUANTITY_MANDATORY_MESSAGE: 'Enter value in multiples of 1',
        DEBIT_ACCOUNT: 'Debit A/C',
        AMOUNT: 'Amount',
        DEMAT_VALIDATION_MESSAGE_MIN: 'Please type up to 16 characters.',
        QUANTITY_HINT_MESSAGE: 'Enter value in multiples of',
        BALANCE: 'Balance',
        INSUFFICIENT_BALANCE: 'Insufficient balance',
        HOLDINGS: 'Holdings',
        APPLICATIONS: 'Applications',
        IN_PROCESS_APPLICATIONS: 'In process applications',
        REJECTED_APPLICATIONS: 'Rejected applications',
        TRANCHE_DATE: 'Tranche Date',
        ORDER_NUMBER: 'Order no.',
        QUANTITY_LABEL: 'Quantity purchased',
        INVESTED_AMOUNT: 'Amount invested',
        IN_PROCESS: 'In Process',
        REJECTED: 'Rejected',
        NO_APPLICATIONS_AVAILABLE: 'No SGB applications currently available',
        BUY: 'Buy',
        ORDER_NUMBER_LABEL: 'Order Number',
        APPLICATION_SUBMITTED_SUCCESSFULLY:
          'Success! Your requested purchase of sovereign gold bonds worth ₹{amount} ({gramsUnit} grams) is complete. Your SGB purchase will reflect in your holding and portfolio within 7 working days from the date of issue.',
        BROWSE_OTHER_PRODUCTS: 'Browse other products',
        DONE: 'Done',
        CHECK_STATUS: 'Check status',
        NO_HOLDINGS_AVAILABLE: 'No SGB holdings currently available',
        TOTAL_SGB: 'Total SGB',
        BUY_SOVEREIGN_GOLD_BOND: 'Buy sovereign gold bond',
        SHARE_CERTIFICATES: 'Share certificate(s)',
        QUANTITY_PURCHASED: 'Quantity purchased',
        ESTIMATED_CURRENT_VALUE: 'Estimated current value',
        TOTAL_QUANTITY_PURCHASED: 'Total quantity purchased',
        TOTAL_INVESTED_AMOUNT: 'Total amount invested',
        TRANCHE: 'Tranche',
        LOCK_IN_DATE: 'Lock-in date',
        ALLOTMENT_DATE: 'Allotment date',
        MATURITY_DATE: 'Maturity date',
        APPLIED_QUANTITY: 'Applied quantity',
        APPLIED_AMOUNT: 'Applied amount',
        INTEREST_RATE: 'Interest rate',
        INTEREST_FREQUENCY: 'Interest frequency',
        HALF_YEARLY: 'Half yearly',
        AMOUNT_INVESTED: 'Amount invested',
        YEARLY: 'Yearly',
        MONTHLY: 'Monthly',
        QUARTERLY: 'Quarterly',
        DOWNLOAD_CERTIFICATES: 'Download certificate(s)',
        TRANCHE_APPLICATION_PERIOD: 'Tranche application period',
        ESTIMATED_CURRENT_VALUE_PLACEHOLDER_TEXT: 'Estimated current value considering last 3 days’ average prices',
        TRANSACTIONS: 'Transactions',
        SYSTEMATIC_PLANS: 'Systematic plans',
        DOWNLOAD_SUCCESSFUL: 'Download successful',
        STORAGE_PERMISSION_DENIED: 'Storage permission denied',
        STORAGE_PERMISSION_EVER_DENIED: 'Storage permission denied',
        SGB_DETAILS_CARD: {
          INTEREST_RATE: 'Interest\nrate',
          INTEREST_FREQUENCY: 'Interest\nfrequency',
          ESTIMATED_CURRENT_VALUE: 'Estimated\ncurrent value',
          AMOUNT_INVESTED: 'Amount\ninvested',
          QUANTITY_PURCHASED: 'Quantity\npurchased',
        },
      },
      PORTFOLIO_RECOMMENDATIONS: {
        HEADER: 'Get portfolio \n recommendations',
        SUB_HEADER: 'Enter your investment amount',
        SEE_RECOMMENDATIONS_LABEL: 'See recommended portfolios',
      },
      GOALS: {
        GOAL_COMPLETION: 'Goal completion',
        GOAL_NAME: 'Goal name',
        GOAL_AMOUNT: 'Goal amount',
        CONSIDERING_INFLATION_AT: 'Considering inflation at',
        YOU_WILL_NEED: 'you will need',
        BY: 'by',
        FOR_YOUR: 'for your',
        GET_INVESTMENT_OPTIONS_REDUCE_MONTHLY: 'Get investment options after optimizing savings',
        GOAL_NAME_VALIDATION_MESSAGE: 'Please enter your goal’s name.',
        DUPLICATE_GOAL_NAME_VALIDATION_MESSAGE: 'A goal by this name already exists. Please set a new goal name!',
        GOAL_AMOUNT_MIN_VALIDATION_MESSAGE: 'Please enter a goal amount of at least ₹',
        GOAL_AMOUNT_MAX_VALIDATION_MESSAGE: 'Please enter a goal amount up to ₹',
        CR: 'Cr',
        GOAL_DASH_BOARD_TITLE: 'Goal based investing',
        OPTIMIZE_SAVINGS_TITLE: 'Optimize investment',
        OPTIMIZE_SAVINGS_HEADER_DESCRIPTION: 'Reduce your monthly investment with the following options',
        LUMP_SUM_CONTRIBUTION_TITLE: 'Lump sum contribution',
        LUMP_SUM_CONTRIBUTION_LABEL: 'One time lumpsum',
        LUMP_SUM_CONTRIBUTION_DESCRIPTION: 'Make lump sum contribution & reduce your monthly investment.',
        STEP_UP_SAVINGS_TITLE: 'Step up investment',
        STEP_UP_SAVINGS_LABEL: 'Step up by',
        STEP_UP_SAVINGS_DESCRIPTION: 'Increase your monthly investment every year & reach your goal quicker.',
        EXISTING_SAVINGS_TITLE: 'Include existing savings',
        EXISTING_SAVINGS_LABEL: 'Existing saving amount',
        EXISTING_SAVINGS_DESCRIPTION: 'With this we can calculate what is the additional amount you need to invest.',
        EXISTING_SAVINGS_NOTE: 'Assumed at a growth rate of {growthRate}% per year',
      },
      RECOMMENDED_PORTFOLIO: {
        HEADER: 'Recommended portfolio',
        RECOMMENDED_PORTFOLIO: 'Recommended Portfolio',
        HERE_ARE_PORTFOLIOS_BASED: 'Here are portfolios based on your current risk profile',
        RISK_PROFILE_DISC: 'A {riskProfile} risk profile has {riskProfileDisc}',
        TOTAL_LUMP_SUM_INVESTMENT: 'Total lump sum investment   {amount}',
        TOTAL_SIP_INVESTMENT: 'Total SIP investment   {amount}',
        CHOOSE_MY_OWN_FUNDS: 'Choose my own funds',
        INVEST_NOW: 'Invest now',
        STEP_UP: 'Step-up',
        EDIT_AMOUNT: 'Edit amount',
        DELETE_FUND: 'Delete fund',
        REPLACE_FUND: 'Replace fund',
        REPLACE: 'Replace',
        VIEW_FUND_DETAILS: 'View fund details',
        API_ERROR_MSG: 'Recommended funds currently unavailable',
        HERE_ARE_PORTFOLIOS_BASED_ON_RISK: 'Here are portfolios based on risk profile',
        CAUTIOUS: 'Cautious',
        BALANCED: 'Balanced',
        AGGRESSIVE: 'Aggressive',
        TOOLTIP_MSG: 'Your risk profile defines your appetite for financial risk in investments',
        RISK_PROFILE_ERROR_MSG: 'Sorry! Something went wrong at the moment\nPlease try again in some time.',
      },
      ALTERNATES: {
        HEADER: 'Alternates',
        TOTAL_INVESTED_VALUE: 'Total invested value',
        TOTAL_CURRENT_VALUE: 'Total current value',
        TOTAL_GAIN_LOSS: 'Total gain/loss value',
        ABS_RETURN: 'Absolute return',
        ALL_API_FAIL_MSG: 'Sorry! Something went wrong at the moment\nPlease try again in some time.',
        BOND: 'Bonds',
        PMS: 'Portfolio management services',
        STRUCTUREDPRODUCT: 'Structured products',
        AIF: 'Alternative investment funds',
        OTHERS: 'Others',
        SCHEME_NAME: 'Scheme name',
        INVESTED_VALUE: 'Invested value',
        CURRENT_VALUE: 'Current value',
        VALUATION_DATE: 'Valuation date',
        GAIN_LOSS: 'Gain/loss value',
      },
      TRADING_AND_DEMATS: {
        ACCOUNT_SCREEN_HEADER: 'Success!',
        APPLICATION_SUBMITTED: 'Application Submitted',
        APPLICATION_REJECTED: 'Application Rejected',
        APPLICATION_ERROR: 'Application Error',
        ZERODHA_HEADER_DESC: 'Thank you for choosing IDFC FIRST Zerodha 3-in-1 Account for your broking needs.',
        ZERODHA_FOOTER_EMAIL_DESC: 'Please get in touch with us at',
        ZERODHA_FOOTER_PHONE_DESC: 'for any queries or call us on',
        YOUR_ACCOUNT_WILL_BE: 'Your account will be activated shortly.',
        ACCOUNT_READY_TO_USE: 'Your IDFC FIRST Zerodha 3-in-1 Account is ready for use.',
        START_TRADING: 'Start trading',
        IN_ASSOCIATION_WITH: 'In association with',
        ZERODHA_OPEN_HEADER_DESC:
          'Avail zero brokerage fees and continue to earn high interest on your savings account',
        FEATURES_AND_BENEFITS: 'Features and Benefits',
        TRADING_DEMAT_ACCOUNT: 'Trading & demat account',
        TRADING_DEMAT_ACCOUNT_DESC: 'From India’s largest broker Zerodha',
        ZERO_BROKERAGE: 'Zero brokerage',
        ZERO_BROKERAGE_DESC: 'When you buy or sell shares',
        SEEMLESS_ACCESS: 'Seamless access',
        SEEMLESS_ACCESS_DESC: 'Access to state-of-the-art kite trading platform from Zerodha',
        ONE_CLICK_TRANSFE: 'One click transfer',
        ONE_CLICK_TRANSFE_DESC: 'One click free transfer from bank to trading account',
        ZERODHA_OPEN_FOOTER_DESC:
          'We will auto download your bank statement as required for opening Zerodha trading account',
        OPEN_YOUR_ZERODHA_ACCOUNT: 'Open your Zerodha account',
        DISCLAIMER: 'Disclaimer',
        DISCLAIMER_DESCRIPTION:
          'By clicking on proceed you will be directed to Zerodha.com to complete trading and demat account opening. Also, your bank account statement will download. This can be submitted with Zerodha to open your account',
        PROCEED: 'Proceed',
        ACTIVATE_ZERODHA_ONE_CLICK_HEADER: 'One click transfer',
        ZERODHA_OTP_VERIFICATION_HEADER: 'Verification',
        ZERODHA_TOGGLE_TEXT: 'Do you have an existing account?',
        ZERODHA_TOGGLE_TOOLTIP:
          'Displays the change to reach Zerodha trading portal Kite if you are holding Zerodha demat and trading account',
        DISCLAIMER_NEW_DESCRIPTION:
          'By clicking on proceed you will be directed to Zerodha.com to complete trading and demat account opening. I authorise IDFC FIRST Bank to share the information as may be required to facilitate account opening. You hereby agree to share your account balance post opening of demat and trading account for seamless fund transfer and investment.',
        ZERODHA_TOGGLE_ON_HEADER: 'Investing in Stock markets is now easy, start trading seamlessly',
        LINK_ACCOUNT: 'Link account',
        ZERODHA_LINK_ACCOUNT_DESC: 'Link your IDFC FIRST account with Zerodha to enjoy faster payments and transfer!',
        ACCESS_TRADING_ACC_BTN: 'Access trading account',
        LEAR_MORE: 'Learn more on ',
        ZERODHA_SUPPORT: 'Zerodha Support',
        CURATED_JUST_FOR_YOU: 'Curated just for you',
        INVEST_IN_OUR_CURATED_PORTFOLIOS: 'Invest in our curated portfolios',
        INVEST_IN_OUR_CURATED_PORTFOLIOS_DESC: 'Invest in our portfolios researched and curated specifically for you',
        ZERODHA_ACC_READY_CLICK_HERE_LINK: 'Click here',
        ZERODHA_ACC_READY_CLICK_HERE_DESC: '(To know your account opening status)',
      },
      INVEST_INTO_IPO: {
        SORRY: 'Aw-snap!',
        UNABLE_TO_FIND_EMAIL_ID:
          "We're unable to find your email address in our bank records.\nPlease visit the nearest bank branch to update email address and then try again.",
        GO_TO_ORDER_BOOK: 'Go to Order Book',
        ERROR_MSG_TITLE: 'Technology can be difficult sometimes!',
        ERROR_MSG_TEXT:
          'We are unable to get your order details at the moment. Please come back in sometime and we will have it sorted.',
      },
      ACCESS_RIGHTS: {
        ACCESS_RESTRICTED_EMPTY_TRANCHE: 'Sorry, you have no active tranches presently.',
        ACCESS_RESTRICTED_LINE_ONE: 'Sorry, these investments are unavailable online to your account type.',
        ACCESS_RESTRICTED_LINE_TWO:
          'Please contact your relationship manager or an IDFC FIRST Bank branch near you for further assistance.',
      },
      STP: 'STP',
      SWP: 'SWP',
    },

    INSURANCE: {
      HEADER: 'Insurance',
      INSURANCE_CARD: {
        KNOW_MORE: 'Know more',
      },
      TERM_PLAN: {
        HEADER: 'Term plan',
      },
      TERMPLAN_REIMAGINATION: {
        HEADER: 'Term Quote New Design',
      },
    },
    STORAGE_PERMISSION_DENIED: 'Storage permission denied',
    STORAGE_PERMISSION_EVER_DENIED: 'Storage permission denied permanently',
    CONFIRM_DETAILS: 'Confirm details',
    CONFIRM_PAGE: 'Confirm page',
    RETRY: 'Retry',
    CANCEL: 'Cancel',
    CONFRIM: 'Confirm',
    OK: 'OK',
    CLOSE: 'Close',
    SKIP: 'Skip',
    DONE: 'Done',
    OR: 'OR',
    YES: 'Yes',
    NO: 'No',
    PROCEED: 'Proceed',
    DASHBOARD_ENTRY: 'Dashboard here !',
    OTP_TEXT: 'OTP ',
    NEXT_BUTTON_LABEL: 'Next',
    SUBMIT_BUTTON_LABEL: 'Submit',
    SUBMIT_OTP_BUTTON_LABEL: 'Verify',
    SUBMIT_OTP_BUTTON_ACCESSIBILITY_LABEL: 'Press this button to submit OTP!!!!!!',
    RESEND_OTP: 'Resend OTP',
    ENTER_OTP_MESSAGE: 'Enter OTP',
    OTP_SENT_TO_MOBILE_NUMBER: 'Please enter code sent to your mobile number ending with',
    INCORRECT_OTP_TITLE: 'Error',
    INCORRECT_OTP_MSG: 'Please enter the valid OTP.',
    SORRY: 'Sorry',
    TERMS_AND_CONDITIONS_TITLE: 'Terms and conditions',
    APPLICATION_SUBMITTED: 'Application submitted',
    CHECK_STATUS: 'Check status',
    SUCCESS: 'Success',
    ERROR: 'Error',
    ALMOST_DONE: 'Almost done',
    REPORTS: 'Reports',
    AS_ON_DATE: 'As on date',
    DOWNLOAD: 'Download',
    VIEW_AND_DOWNLOAD: 'View & Download',
    EMAIL_REPORT: 'Email report',
    FROM: 'From',
    TO: 'To',
    NEW_USER_WELCOME: {
      TAKE_A_TOUR: 'Take a tour',
      SKIP_A_TOUR: 'Skip a tour',
      SYSTEM: 'System',
      DETAILS: 'Details',
    },
  },
});

export default ComponentConstants;
