const TRACING_ACTIONS = {
  DOWNLOAD_SWIFT_COPY: 'Download Swift Copy',
  DOWNLOAD_PDF: 'Download Pdf',
  DOWNLOAD_PURPOSE_CODE_LIST: 'Download Purpose Code list',
  UPLOAD_DISBURSAL_PROOF_DOCUMENT: 'Upload Disbursal Proof Document',
  SUBMIT_DISPOSAL_INSTRUCTIONS: 'Submit Disposal Instructions',
  FILL_DISPOSAL_INSTRUCTIONS: 'Fill Disposal Instructions',
  CREATE_DEPOSIT: '{profile_type}_create_{deposit_type}_deposit',
  CLOSE_DEPOSIT: '{profile_type}_close_{deposit_type}_deposit',
  LOGIN_MPIN: 'login_mpin',
  UPDATE_ACCOUNT_LEVEL_DAILY_LIMIT: 'Update Account Level Daily Limit',
  UPDATE_ENTITY_LEVEL_DAILY_LIMIT: 'Update Entity Level Daily Limit',
  UPDATE_ENTITY_AND_ACCOUNT_LIMIT: 'Update Entity and Account Limit',
  CREATE_OD: 'create_od',
  CLOSE_OD: 'close_od',
  EEFC_TO_INR_CONVERT: 'eefc_to_inr_convert',
  ADD_EXISTING_MAKER: 'add_existing_maker',
  ADD_NEW_MAKER: 'add_new_maker',
  GET_PAYMENTS_VPA: 'get_payments_vpa',
  GET_PAYMENTS_VERIFY_VPA: 'get_payments_verify_vpa',
  GET_PAYMENTS_AUTO_SELECT: 'get_payments_autoselect',
  GET_MAKER_ROLES: 'get_maker_roles',
  GET_MAKER_UNASSOCIATED_ACCOUNTS: 'get_maker_unassociated_accounts',
  GET_ACCOUNTS_INFO: 'get_accounts_info',
  GET_ACCOUNT_PERMISSIONS: 'Get Account Permissions',
  GET_MAKER_DETAILS: 'Get Maker Details',
  GET_ALL_ACCOUNTS_FOR_MAKER: 'Get All Accounts which can be associated to maker',
  UPDATE_MAKER_INFO: 'Update Maker Information',
  UPDATE_MAKER_PERMISSIONS: 'Update Maker Permissions',
  RESOLVE_MAPPER_LINK_UUID: 'Resolve mapper link UUID',
  PFM: {
    FETCH_MENIGA_ACCOUNTS: 'PFM - Fetch Meniga Accounts',
    FETCH_TRANSACTIONS: 'PFM - Fetch Transactions',
    FETCH_UNCERTAIN_TRANSACTIONS_COUNT: 'PFM - Fetch Uncertain Transactions Count',
    FETCH_RECENT_TRANSACTIONS: 'PFM - Fetch Recent Transactions',
    FETCH_TRANSACTION_DETAILS: 'PFM - Fetch Transaction Details',
    PAY_FETCH_TRANSACTIONS: 'PFM - (Pay) Fetch Transactions',
    PAY_SEARCH_TRANSACTIONS: 'PFM - (Pay) Fetch Search Transactions',
    PAY_FILTER_TRANSACTIONS: 'PFM - (Pay) Fetch Filter Transactions',
    PAY_FETCH_SUGGESTIONS: 'PFM - (Pay) Fetch Suggestions',
    PAY_DOWNLOAD_TRANSACTIONS: 'PFM - (Pay) Download Transactions or Details',
    DASHBOARD_FETCH_TRANSACTIONS: 'PFM - (Dashboard) Fetch Transactions',
    CASHFLOW_FETCH_TRANSACTIONS: 'PFM - (Cashflow) Fetch Transactions',
    CASHFLOW_FETCH_SERIES: 'PFM - (Cashflow) Fetch Series',
    INVESTMENT_DETAILS: 'PFM - (Cashflow) Investment Details',
    CASHFLOW_FETCH_ANALYSIS: 'PFM - (Cashflow) Fetch Analysis',
    CASHFLOW_FETCH_TRACKER: 'PFM - (Cashflow) Fetch Tracker',
    EDIT_CATEGORY_UPDATE_CATEGORY: 'PFM - (Edit Category) Update Categories',
    EDIT_CATEGORY_FETCH_CATEGORY: 'PFM - (Edit Category) Fetch Categories',
    UPCOMING_FETCH_TRANSACTIONS: 'PFM - (Upcoming) Fetch Transactions',
    UPCOMING_FETCH_TRANSACTION_DETAILS: 'PFM - (Upcoming) Fetch Transaction Details',
    UPCOMING_SMART_SUGGESTIONS_NOT_HELPFUL_DECLINE: 'PFM - (Upcoming) Smart suggestions not helpful decline',
    UPCOMING_SMART_SUGGESTIONS_PAID_DECLINE: 'PFM - (Upcoming) Smart suggestions paid decline',
    UPCOMING_FETCH_PERMISSIONS: 'PFM - (Upcoming) Fetch permissions',
    FETCH_UNCERTAIN_TRANSACTIONS: 'PFM - (Pay) Fetch uncertain transactions',
    MY_FINANCES_FETCH_CREDIT_CARD_REWARDS: 'PFM - (My Finances) Fetch credit card rewards',
    FETCH_PFM_STATIC_CONTENT: 'PFM - Fetch pfm static content',
    MY_FINANCES_FETCH_USER_INTEREST: 'PFM - (My Finances) Fetch user interest',
    MY_FINANCES_FETCH_GOALS_CATEGORIES: 'PFM - (My Finances) Fetch goals categories',
    FETCH_PERMISSIONS: 'PFM - Fetch Permissions',
  },
  SPLASH: {
    IDFC_PRE_LOGIN: 'IDFC_PRE_LOGIN',
  },
  DEBIT_CARDS: {
    GET_DEBIT_CARDS_V2: 'RAS- get debit cards V2',
    GET_DEBIT_CARDS_V3: 'RAS- get debit cards V3',
  },
  EDIT_OD: 'Modify OD against FD',
};

export default TRACING_ACTIONS;
