const passConst = 'password';
const passCap = 'Password';
export const EtbNtbStatus = {
  NTB: 'ntb',
  ETBWithIndividualRelationship: 'ETB Individual Relationship',
  ETBWithExistingEntityRelationship: 'ETB with existing Enity Realtionship',
  ETBwithNewEnityRealtionship: 'ETB with new Entity Relationship',
  Dorm: 'DORM',
  Dormant: 'DORMANT',
};

export const MasterDataLimits = {
  cityState: 10,
  branches: 10,
  country: 500,
  pincodes: 500,
};

export const DashboardLimits = {
  allLeads: 500,
  boUserId: 2,
};

export const NetworkCallExecutionStatus = {
  fetching: 'fetching',
  succeed: 'succeed',
  failed: 'failed',
};

export const Constants = {
  Input_Text_Length: 30,
  Mobile_No_Length: 10, // with +91 & space
  Pan_No_Length: 10,
  Verification_Code_Const: 6,
  Annual_Income_Length: 9,
  Fund_Amount_Length: 6,
  Ifsc_No_Length: 11,
  Bank_Acc_No_Length: 18,
  Address_Parition: 40,
  Pincode_Length: 6,
  Fund_Amount_Max_length: 20,
  Fund_Amount_Min_Value: 0,
  Fund_Amount_Max_Value: 1000000,
};

export const KeyboardTypes = {
  Default_Keyboard: 'default',
  Number_Pad: 'number-pad',
  Decimal_Pad: 'decimal-pad',
  Numeric: 'numeric',
  Email_Address: 'email-address',
  Phone_PAD: 'phone-pad',
};

export const KeyboardConst = {
  Mobile: 'mobile',
  Sentences: 'sentences',
  Characters: 'characters',
  None: 'none',
};

export const FORMFIELDS = {
  BOLogin: {
    userName: 'userName',
    password: passConst,
  },
  CreateLead: {
    businessType: 'businessType',
    firstName: 'firstName',
    lastName: 'lastName',
    middleName: 'middleName',
    mobileNumber: 'mobileNumber',
    pan: 'pan',
  },
  PANDetails: {
    pan: 'pan',
    panHolderName: 'panHolderName',
    docType: 'docType',
    dob: 'dob',
    dlNo: 'dlNo',
    docExp: 'docExp',
    voterID: 'voterID',
    passportNo: 'passportNo',
    fileNumber: 'fileNumber',
    aadharNo: 'aadharNo',
  },
  EntityAddressProof: {
    docTypeEntity: 'documentType',
    idNumberEntity: 'idNumberEntity',
    idNumberCommunication: 'idNumberCommunication',
    idNumberAddressProof: 'idNumberAddressProof',
    dob: 'dob',
    dobRent: 'dobRent',
    dobAddress: 'dobAddress',
    dlNo: 'dlNo',
    docExp: 'docExp',
    voterID: 'voterID',
    passportNo: 'passportNo',
    fileNumber: 'fileNumber',
    docExpiryDate: 'docExpiryDate',
    dateOfAgreement: 'dateOfAgreement',
    communicationDropdown: 'communicationDropdown',
    bsPassword: 'bsPassword',
    bankName: 'bankName',
    bsAccountNumber: 'bsAccountNumber',
    bsIFSCCode: 'bsIFSCCode',
    bsStatementStartDate: 'bsStatementStartDate',
    bsStatementEndDate: 'bsStatementEndDate',
    aadharNo: 'aadharNo',
  },
  AddBusinessDetails: {
    entityName: 'entityName',
    accountTitle: 'accountTitle',
    iECCodeOptional: 'iECCodeOptional',
    websiteOptional: 'websiteOptional',
    bussAddressLine1: 'bussAddressLine1',
    bussAddressLine2: 'bussAddressLine2',
    bussAddressLine3: 'bussAddressLine3',

    landmarkOpt: 'landmarkOpt',
    cityBal: 'cityBal',
    districtBal: 'districtBal',
    pinCodeBal: 'pinCodeBal',
    stateBal: 'stateBal',
    countryBal: 'countryBal',
    mobileBal: 'mobileBal',
    landlineOptional: 'landlineOptional',
    emailBal: 'emailBal',
    communicationAL1: 'communicationAL1',
    communicationAL2: 'communicationAL2',
    communicationAL3: 'communicationAL3',
    landmarkOptCAL: 'landmarkOptCAL',
    cityCAL: 'cityCAL',
    districtCAL: 'districtCAL',
    pincodeCAL: 'pincodeCAL',
    stateCAL: 'stateCAL',
    countryCAL: 'countryCAL',
    mobileCAL: 'mobileCAL',
    landlineCAL: 'landlineCAL',
    emailCAL: 'emailCAL',
    lineOfBusiness: 'lineOfBusiness',
    natureOfIndustry: 'natureOfIndustry',
    annualTurnover: 'annualTurnover',
    dateOfIncorporation: 'dateOfIncorporation',
    internationalTradeTurnover: 'internationalTradeTurnover',
  },
  AddProprietorDetails: {
    salutation: 'salutation',
    firstName: 'firstName',
    middleName: 'middleName',
    lastName: 'lastName',
    dob: 'dob',
    dmob: 'dmob',
    yob: 'doy',
    gender: 'gender',
    fatherName: 'fatherName',
    motherMaidenName: 'motherMaidenName',
    mothersName: 'mothersName',
    nationality: 'nationality',
    countryOfBirth: 'countryOfBirth',
    countryOfTaxRes: 'countryOfTaxRes',
    address1: 'address1',
    address2: 'address2',
    address3: 'address3',
    landmark: 'landmark',
    city: 'city',
    district: 'district',
    pincode: 'pincode',
    state: 'state',
    country: 'country',
    mobile: 'mobile',
    landline: 'landline',
    email: 'email',
  },
  AddInitialFunds: {
    chequeNumber: 'chequeNumber',
    chequeDate: 'chequeDate',
    ifscCode: 'ifscCode',
    branchName: 'branchName',
    bankName: 'bankName',
    fundAmount: 'fundAmount',
    fundingAmount: 'Enter funding amount*',
    funds: 'funds',
    uploadFundDoc: 'uploadFundDoc',
    uploadFundFileName: 'uploadFundFileName',
    fundProceedButton: 'fundProceedButton',
  },
  NomineeDetailsWithAddress: {
    nomineeFirstName: 'nomineeFirstName',
    nomineeMiddleName: 'nomineeMiddleName',
    nomineeLastName: 'nomineeLastName',
    relationShip: 'relationShip',
    birthDate: 'birthDate',
    communicationAL1: 'communicationAL1',
    communicationAL2: 'communicationAL2',
    communicationAL3: 'communicationAL3',
    nomineeLandmark: 'nomineeLandmark',
    city: 'city',
    state: 'state',
    district: 'district',
    country: 'country',
    pincode: 'pincode',
    guardianFirstName: 'guardianFirstName',
    guardianMiddleName: 'guardianMiddleName',
    guardianLastName: 'guardianLastName',
    guardianAddress1: 'guardianAddress1',
    guardianAddress2: 'guardianAddress2',
    guardianAddress3: 'guardianAddress3',
    mentionNomineeOnAccount: 'mentionNomineeOnAccount',
    wantToAddNominee: 'wantToAddNominee',
    nomineeAddressSameAsProprietor: 'nomineeAddressSameAsProprietor',
    guardianCity: 'guardianCity',
    guardianLandmark: 'guardianLandmark',
    guardianState: 'guardianState',
    guardianDistrict: 'guardianDistrict',
    guardianPincode: 'guardianPincode',
    guardianCountry: 'guardianCountry',
    guardianAddressSameAsNominee: 'guardianAddressSameAsNominee',
  },
  ProprietorDeclaration: {
    proprietorsName: 'proprietorsName',
    fatherName: 'fathersName',
    maidenName: 'maidenName',
    mothersName: 'mothersName',
    maritalStatus: 'maritalStatus',
    residentialStatus: 'residentialStatus',
    proprietorsDateofBirth: 'proprietorsDateofBirth',
    countryofBirth: 'countryofBirth',
    countryofTaxResidency: 'countryofTaxResidency',
    TINIssueingCountry: 'TINIssueingCountry',
  },
  GSTAnnexure: {
    state: 'state',
    registrationNumber: 'registrationNumber',
    remarks: 'remarks',
    addressLine1: 'addressLine1',
    addressLine2: 'addressLine2',
    addressLine3: 'addressLine3',
    GSTStatus: 'GSTStatus',
    exemptedFromGST: 'exemptedFromGST',
    exemptionLevel: 'exemptionLevel',
    relatedPersonToIDFC: 'relatedPersonToIDFC',
    addressType: 'addressType',
    addressAsPerGSTN: 'addressAsPerGSTN',
    gstCertificate: 'gstCertificate',
    gstCertificateUploadDone: 'gstCertificateUploadDone',
  },
  CreditFacilityDeclaration: {
    bankName: 'bankName',
    branchName: 'branchName',
    facilityType: 'facilityType',
    accountNumber: 'accountNumber',
    sanctionedAmount: 'sanctionedAmount',
    feedback: 'feedback',
    radioValue: 'radioValue',
    creditFacility: 'creditFacility',
    bankDetails: 'bankDetails',

    bankNameArray: [
      'bankName0',
      'bankName1',
      'bankName2',
      'bankName3',
      'bankName4',
      'bankName5',
      'bankName6',
      'bankName7',
      'bankName8',
      'bankName9',
      'bankName10',
      'bankName11',
      'bankName12',
      'bankName13',
      'bankName14',
    ],
    branchNameArray: [
      'branchName0',
      'branchName1',
      'branchName2',
      'branchName3',
      'branchName4',
      'branchName5',
      'branchName6',
      'branchName7',
      'branchName8',
      'branchName9',
      'branchName10',
      'branchName11',
      'branchName12',
      'branchName13',
      'branchName14',
    ],
    facilityTypeArray: [
      'facilityType0',
      'facilityType1',
      'facilityType2',
      'facilityType3',
      'facilityType4',
      'facilityType5',
      'facilityType6',
      'facilityType7',
      'facilityType8',
      'facilityType9',
      'facilityType10',
      'facilityType11',
      'facilityType12',
      'facilityType13',
      'facilityType14',
    ],
    accountNumberArray: [
      'accountNumber0',
      'accountNumber1',
      'accountNumber2',
      'accountNumber3',
      'accountNumber4',
      'accountNumber5',
      'accountNumber6',
      'accountNumber7',
      'accountNumber8',
      'accountNumber9',
      'accountNumber10',
      'accountNumber11',
      'accountNumber12',
      'accountNumber13',
      'accountNumber14',
    ],
    sanctionedAmountArray: [
      'sanctionedAmount0',
      'sanctionedAmount1',
      'sanctionedAmount2',
      'sanctionedAmount3',
      'sanctionedAmount4',
      'sanctionedAmount5',
      'sanctionedAmount6',
      'sanctionedAmount7',
      'sanctionedAmount8',
      'sanctionedAmount9',
      'sanctionedAmount10',
      'sanctionedAmount11',
      'sanctionedAmount12',
      'sanctionedAmount13',
      'sanctionedAmount14',
    ],
  },
  ProductSelection: {
    caVariant: 'caVariant',
    mobileNumber: 'mobileNumber',
    contactPerson: 'contactPerson',
  },
  CustomerInfo: {
    barcode: 'barcode',
  },
  BankUse: {
    leadID: 'leadID',
    variantName: 'variantName',
    variantCode: 'variantCode',
    leadConverter: 'leadConverter',
    leadGenerator: 'leadGenerator',
    leadwarmer: 'leadwarmer',
    promoCode: 'promoCode',
    campaignCode: 'campaignCode',
  },
  SiteVerificationReport: {
    sourceOfLead: 'sourceOfLead',
    mentionOtherSourceOpt: 'mentionOtherSourceOpt',
    pvtLtdPROBE: 'pvtLtdPROBE',
    natureOfBusiness: 'natureOfBusiness',
    nameOfCompanyInAbbreviation: 'nameOfCompanyInAbbreviation',
    matchingAbbreviation: 'matchingAbbreviation',
    easeOfLocatingSite: 'easeOfLocatingSite',
    physicalAppearanceBuilding: 'physicalAppearanceBuilding',
    addressLocality: 'addressLocality',
    mentionAddressLocality: 'mentionAddressLocality',
    typeOfOffice: 'typeOfOffice',
    natureOfOwnershipAddress: 'natureOfOwnershipAddress',
    entityDirectorOpt: 'entityDirectorOpt',
    yearsOperatingAddress: 'yearsOperatingAddress',
    operatedMultipleLocation: 'operatedMultipleLocation',
    reasonMultipleOpt: 'reasonMultipleOpt',
    numberOfSuchAddresses: 'numberOfSuchAddresses',
    reasonDifferentCommAddressOpt: 'reasonDifferentCommAddressOpt',
    productDealing: 'productDealing',
    IDFCFIRSTBankCustomerID: 'IDFCFIRSTBankCustomerID',
    detailsOfRelationship: 'detailsOfRelationship',
    affiliationsMembership: 'affiliationsMembership',
    reasonMoreThanOneCompanyOpt: 'reasonMoreThanOneCompanyOpt',
    reasonDifferentCommAddressReqComm: 'reasonDifferentCommAddressReqComm',
    employeeSeenWorking: 'employeeSeenWorking',
    yearsOperatingAddressComm: 'yearsOperatingAddressComm',
    reasonMoreThanOneCompanyOptComm: 'reasonMoreThanOneCompanyOptComm',
    designationDM: 'designationDM',
    nameDM: 'nameDM',
    nameSignature: 'nameSignature',
    ageSignature: 'ageSignature',
    holdingPositionSignature: 'holdingPositionSignature',
    noOfYearsExperienceSignature: 'noOfYearsExperienceSignature',
    makerNameRecommendation: 'makerNameRecommendation',
    designationRecommendation: 'designationRecommendation',
    employeeCodeRecommendation: 'employeeCodeRecommendation',
    selectDateRecommendation: 'selectDateRecommendation',
    commentRecommendationOpt: 'commentRecommendationOpt',
    checkerNameRecommendation: 'checkerNameRecommendation',
    designationRecommendationSecond: 'designationRecommendationSecond',
    detailedFeedbackNeighbour: 'detailedFeedbackNeighbour',
    natureOfAbbreviationUsed: 'natureOfAbbreviationUsed',
  },
};

//Upload Api supported Document type
export const UploadApiDocumentTypes = {
  Address_Proof: 'Address Proof',
  Id_Proof: 'Id Proof',
  Communication_Address_Proof: 'Communication Address Proof',
  Annexure: 'Annexure',
  AOF: 'AOF',
  Approval_Doc: 'Approval Doc',
  BR: 'BR',
  Director_List: 'Director List',
  EDD: 'EDD',
  Form6061: 'Form6061',
  Funding_Cheque: 'Funding Cheque',
  GST_1: 'GST 1',
  GST_2: 'GST 2',
  GST_3: 'GST 3',
  GST_4: 'GST 4',
  GST_5: 'GST 5',
  GST_Acknowledgement_Registration: 'GST Acknowledgement Registration',
  GST_Annexure: 'GST Annexure',
  GST_Exemption: 'GST Exemption',
  Initial_Cheque: 'Initial Cheque',
  Initial_Cheque_Payment: 'Initial Cheque Payment',
  MOA_AOA: 'MOA AOA',
  MPA: 'MPA',
  MPA_Form: 'MPA Form',
  Partnership_Deed: 'Partnership Deed',
  Photo: 'Photo',
  Request_Form: 'Request Form',
  Shop_Images: 'Shop Images',
  Signature: 'Signature',
  SVR: 'SVR',
  TDD: 'TDD',
  Other: 'Other',
  VKYC_Agent_Video: 'VKYC_Agent_video',
  VKYC_Customer_Video: 'VKYC_Customer_video',
  VKYC_PAN: 'VKYC_PAN',
  VKYC_Selfie: 'VKYC_Selfie',
  VKYC_Wet_Signature: 'VKYC_Wet_signature',
  VKYC_Profile_Report: 'VKYC_Profile_report',
  Bank_Statements: 'Bank Statements',
  Financial_Statements: 'Financial Statements',
  Firm_Establisment: 'Firm Establisment',
  Reference_Check: 'Reference check',
  Collateral_Proof: 'Collateral proof',
  ITR: 'ITR',
  Self_Certified_Docs: 'Self Certified docs',
  BUSINESS: 'BUSINESS',
  Account_Opening_FATCA_CRS_DECLARATION_FOR_FINANCIAL_INSTITUTIONS:
    'Account_Opening_FATCA_CRS_DECLARATION_FOR_FINANCIAL_INSTITUTIONS',
  Account_Opening_FATCA_CRS_DECLARATION_FOR_NON_FINANCIALINSTITUTION:
    'Account_Opening_FATCA_CRS_DECLARATION_FOR_NON_FINANCIALINSTITUTION',
  FRRO: 'FRRO',
  CIN: 'CIN',
  Registration_Certificate: 'Registration certificate',
  Trust_Deed: 'Trust Deed',
  Board_Resolution: 'Board Resolution',
  CAM: 'CAM',
  Sanction_Letter: 'Sanction letter',
  Security_Documents: 'Security Documents',
  Name_Clearance: 'Name Clearance',
  Covenants: 'Covenants',
  Insurance: 'Insurance',
  IEC_Supporting_Document: 'IEC Supporting Document',
};

export const UploadApiDocumentName = {
  'Aadhaar Card': 'Aadhaar Card',
  'Driving License': 'Driving License',
  'NREGA Card': 'NREGA Card',
  passport: 'Passport',
  'Voter ID': 'Voter Identity Card',
  'NPR Letter': 'Other',
  'Marriage Certificate': 'Other',
  'Funding Cheque': 'Funding Cheque',
  'Initial Cheque': 'Initial Cheque',
  Entity_Name_Mismatch: 'Other',
  GST_Registration_Certificate: 'GST Registration Certificate',
};

export const UploadApiDocumentFileName = {
  ProprietorIdentityProof: 'Sign_1_Identity_Proof_',
  ProprietorAddressProof: 'Sign_1_Address_Proof_',
  ProofOfName: 'Sign_1_Proof_Of_Name_Change_',
  EntityIdentityProof: 'Entity_Identity_Proof_',
  EntityBusinessAddressProof: 'Entity_Business_Address_Proof_',
  EntityCommunicationAddressProof: 'Entity_Communication_Address_Proof_',
  IECSupportingDocument: 'IEC_Supporting_Document_',
  ProprietorPhoto: 'Sign_1_Photo_',
  ProprietorSignature: 'Sign_1_Signature_',
  NegativeScreeningReport: 'Negative_Screening_Report',
  BureauResponse: 'Bureau_Response',
  FICOResponse: 'FICO_Response',
  GSTCertificateForGSTAnnexure: 'GST_Certificate_For_GST_Annexure_',
  MITCForm: 'MITC_Form_',
  FundingCheque: 'Funding_Cheque_',
  CancelledCheque: 'Cancelled_Cheque_',
  Perfios_Report: 'Perfios_Report',
  EntityNameMismatchDeclaration: 'Entity_Name_Mismatch_Declaration_',
  DateOfBirthMismatchDeclaration: 'Date_Of_Birth_Mismatch_Declaration_',
  PhotoOfCustomerOnAadhar: 'Photo_Of_Customer_On_Aadhar',
  SVRBusinessBoardPhoto: 'SVR_Business_Board_Photo_',
  SVRBusinessProductsPhoto: 'SVR_Business_Products_Photo_',
  SVRCustomerInPremisePhoto_: 'SVR_Customer_In_Premise_Photo_',
  SystemApprovalNameofException: 'SystemApproval_NameofException_',
  ManualApprovalNameofException: 'ManualApproval_NameofException_',
  SnippetPOCDocumentName: 'Snippet_POCDocumentName_',
  EAOF: 'E-AOF',
  CRILC_Report: 'CRILC_Report',
  Other_Documents: 'Other_Documents',
  TDD: 'TDD',
  GST_Exemption: 'GST_Exemption',
  GST_1: 'GST_1',
  RERA_ANNEXURE: 'RERA_ANNEXURE',
  ESCROW_ANNEXURE: 'ESCROW_ANNEXURE',
  Sign_1_PAN: 'Sign_1_PAN',
  Entity_PAN: 'Entity_PAN',
  Karza_DocumentType: 'Karza_DocumentType',
  Snippet_DocumentType: 'Snippet_DocumentType',
  Digilocker_DocumentType: 'Digilocker_DocumentType',
  SVR: 'SVR',
  EDD: 'EDD',
};

export const ErrorPopUpTypes = {
  ok: {
    title: 'System Error',
    message: 'Please try after sometime',
    actionName: 'OK',
  },
  dummy: {
    title: '',
    message: 'Please try after some time',
    actionName: 'OK',
  },
  networkError: {
    title: 'Network Error',
    message: 'Please try after some time',
    actionName: 'OK',
  },
  retry: {
    title: 'Retry',
    message: 'Please try after sometime',
    actionName: 'Retry',
  },
  invalidPan: {
    title: 'Please enter valid PAN',
    message: 'Please check the PAN entered.',
    actionName: 'Back',
  },
  mismatchPan: {
    title: 'Mismatch found in PAN!',
    message: 'Please check the PAN entered.',
    actionName: 'Back',
  },
  uploadError: {
    title: 'Document Upload Error',
    message: 'Please try after some time',
    actionName: 'OK',
  },
  invalidDocVerify: {
    title: 'Cannot validate the document',
    message: 'please provide other document or Proceed with same document',
    actionName: 'OK',
  },
  uploadAPI:
    'Uh-oh! Uploaded document is incorrect. Upload correct document and retry.',
  uploadIncorrectFormat:
    'Aw-snap! The file uploaded is in a different format. Upload files only in PDF, TIFF & JPG formats and retry. ',
  uploadCurrupted:
    'Uh-oh! Uploaded document is not clear. Upload correct document and retry.',
  uploadTooLarge:
    'Aw-snap! Uploaded file size is more than 10 MB. Upload file smaller than 10 MB and retry.',
  aadharNoNotMatch: {
    title: 'Fingerprint does not match entered Aadhar',
    message:
      'Make sure to provide correct fingerprint or update the Aadhar number.',
    actionName: 'OK',
  },
  dlNotActive: {
    title: 'System Error',
    message:
      'Oh-no! Your License validity has expired. Please provide another document to proceed.',
    actionName: 'OK',
  },
  voterIdNotActive: {
    title: 'System Error',
    message:
      'Oh-no! Your Voter ID is not active. Please provide another document to proceed.',
    actionName: 'OK',
  },
  fileNumberNotActive: {
    title: 'System Error',
    message:
      'Oh-no! The File Number you have entered is inactive.Please provide another document to proceed.',
    actionName: 'OK',
  },
  aadharNotActive: {
    title: '',
    message:
      'Oh-no! Your AADHAAR number is not active. Provide another document to proceed.',
    actionName: 'OK',
  },
  aadharApiFail: {
    title: 'System Error',
    message: 'Please proceed with some other document',
    actionName: 'OK',
  },
  aadharDeviceNotConnect: {
    title: 'Biometric device not connected',
    message: 'Please check or proceed with another document',
    actionName: 'OK',
  },
  aadhaFringerprint: {
    title: 'Take fingerprint of the customer on the Biometric device',
    message: '',
    actionName: 'OK',
  },
  aadharBluetoothoff: {
    title: 'Bluetooth device not enable',
    message: 'Please is enable Bluetooth of device',
    actionName: 'OK',
  },
  aadharBluetoothPermission: {
    title: 'Bluetooth Permission',
    message: 'Please is enable Bluetooth Permission',
    actionName: 'OK',
  },
  bsAddressNotAvailable: {
    title: 'Entity Address is not available!',
    message: 'Unfortunately, entity address proof is not available.',
    subMessage1: ' Upload another document to proceed.',
    actionName: 'Select Other Entity Address Proof',
    width: '80%',
    top: 80,
  },
  bsbankNameMismatch: {
    title: 'Mismatch found in selected Bank Name and uploaded E-pdf!',
    message:
      "Uh-oh! Seems like there's a mismatch in your Bank name. Select the correct Bank name or upload correct E-PDF. ",
    actionName: 'Back',
    width: '50%',
    top: 60,
  },
  bsInvalidBankStatement: {
    title: 'Please upload the Bank Statement for 3 months!',
    message: 'Uh-oh! Your bank statement is of ',
    subMessage1: 'less than 3 months.',
    subMessage2: ' Please check and re-upload the correct document.',
    actionName: 'Back',
    width: '50%',
    top: 0,
  },
  bsAccountNotActivated: {
    title: 'Account not active!',
    actionName: 'Select Other Entity Address Proof',
    message:
      'Aw-snap! Account number in the Bank statement is not active. Proceed with ',
    subMessage1: ' another document type.',
    width: '80%',
    top: 60,
  },
  bsPanMismatch: {
    title: 'Mismatch found in PAN!',
    message: 'Please check the PAN entered.',
    actionName: 'Back',
    width: '50%',
    top: 70,
  },
  retryMasterData: {
    title: 'MasterData Failure',
    message:
      "Master data fetcing is failed, You can't proceed furthure. Please try again.",
    actionName: 'Retry',
  },
  builtinCamera: {
    title: 'Upload Document',
    message: '',
    actionName: 'Cancel',
  },
  builtinCameraError: {
    title: 'System Error!',
    message:
      'Please upload the document form One Drive or try again after some time.',
    actionName: 'Cancel',
  },
  builtinCameraDelete: {
    title: 'Delete Image!',
    message: 'Are you sure you want to delete the captured image?',
    actionName: 'Delete',
  },
};

// Test ID's for Unit Testing & QA Team
export const TestIds = {
  login_username: 'username',
  login_password: passConst,
  login_button: 'loginButton',
  proceedBtn: 'proceedButton',
  btnOk: 'OKButton',
  btnCancel: 'cancelButton',
  btnBack: 'btnBack',
  btnLogout: 'btnLogout',
  KnowledgeSharingPopUp: 'KnowledgeSharingPopUp',

  // Application Steps
  btnDashboard: 'btnDashboard',
  steps_card_click: 'steps_card_click',
  steps_dashboard: 'steps_dashboard',

  // bank use
  progress_header_back: 'progressHeaderBack',
  bu_leadID: 'leadID',
  bu_variantName: 'variantName',
  bu_variantCode: 'variantCode',
  bu_leadConverter: 'leadConverter',
  bu_leadGenerator: 'leadGenerator',
  bu_leadwarmer: 'leadwarmer',
  bu_promoCode: 'promoCode',
  bu_campaignCode: 'campaignCode',
  bu_proceedButton: 'buProceedButton',
  bu_siteVerificationChbox: 'siteVerificationCheckbox',
  bu_kycVerificationChbox: 'kycVerificationCheckbox',
  bu_signVerificationChbox: 'signVerificationCheckbox',
  bu_communicationAddressRadioButtom: 'communicationAddressRadioButtom',
  bu_businessAddressRadioButtom: 'businessAddressRadioButtom',

  //For Add Business Details
  abd_entityName: 'abd_entityName',
  abd_accountTitle: 'abd_accountTitle',
  abd_lineOfBusiness: 'abd_lineOfBusiness',
  abd_natureOfIndustry: 'abd_natureOfIndustry',
  abd_dateOfIncorporation: 'abd_dateOfIncorporation',
  abd_annualTurnover: 'abd_annualTurnover',
  abd_iECCodeOptional: 'abd_iECCodeOptional',
  abd_internationalTradeTurnover: 'abd_internationalTradeTurnover',
  abd_websiteOptional: 'abd_websiteOptional',
  abd_bussAddressLine1: 'abd_bussAddressLine1',
  abd_bussAddressLine2: 'abd_bussAddressLine2',
  abd_bussAddressLine3: 'abd_bussAddressLine3',
  abd_landmarkOpt: 'abd_landmarkOpt',
  abd_cityBal: 'abd_cityBal',
  abd_districtBal: 'abd_districtBal',
  abd_pinCodeBal: 'abd_pinCodeBal',
  abd_stateBal: 'abd_stateBal',
  abd_countryBal: 'abd_countryBal',
  abd_mobileBal: 'abd_mobileBal',
  abd_landlineOptional: 'abd_landlineOptional',
  abd_emailBal: 'abd_emailBal',
  abd_communicationAL1: 'abd_communicationAL1',
  abd_communicationAL2: 'abd_communicationAL2',
  abd_communicationAL3: 'abd_communicationAL3',
  abd_landmarkOptCAL: 'abd_landmarkOptCAL',
  abd_cityCAL: 'abd_cityCAL',
  abd_districtCAL: 'abd_districtCAL',
  abd_pincodeCAL: 'abd_pincodeCAL',
  abd_stateCAL: 'abd_stateCAL',
  abd_countryCAL: 'abd_countryCAL',
  abd_mobileCAL: 'abd_mobileCAL',
  abd_landlineCAL: 'abd_landlineCAL',
  abd_emailCAL: 'abd_emailCAL',
  abd_proceedButton: 'abd_proceedButton',
  abd_dummyNavButton: 'abd_dummyNavButton',

  //Add Initial Funds
  aif_pan: 'aif_pan',
  aif_panHolderName: 'aif_panHolderName',
  aif_proceedButton: 'aif_proceedButton',
  aif_funds: 'aif_funds',
  aif_chequeNumber: 'aif_chequeNumber',
  aif_chequeDate: 'aif_chequeDate',
  aif_ifscCode: 'aif_ifscCode',
  aif_branchName: 'aif_branchName',
  aif_bankName: 'aif_bankName',
  aif_uploadFundDoc: 'aif_uploadFundDoc',
  aif_uploadFundFileName: 'aif_uploadFundFileName',
  aif_fundProceedButton: 'aif_fundProceedButton',
  aif_dummyNavButton: 'aif_dummyNavButton',

  // Customer Info Form
  cif_middleName: 'cif_middleName',
  cif_proceedButton: 'cif_proceedButton',
  cif_dummyNavButton: 'cif_dummyNavButton',

  //Digital Declaration
  dgDec_proceedButton: 'dgDec_proceedButton',
  dgDec_dummyNavButton: 'dgDec_dummyNavButton',

  //Proprieter Declarations
  dgDec_proprietorsName: 'dgDec_proprietorsName',
  dgDec_fathersName: 'dgDec_fathersName',
  dgDec_maidenName: 'dgDec_maidenName',
  dgDec_mothersName: 'dgDec_mothersName',
  dgDec_maritalStatus: 'dgDec_maritalStatus',
  dgDec_residentialStatus: 'dgDec_residentialStatus',
  dgDec_proprietorsDateofBirth: 'dgDec_proprietorsDateofBirth',
  dgDec_countryofBirth: 'dgDec_countryofBirth',
  dgDec_countryofTaxResidency: 'dgDec_countryofTaxResidency',
  dgDec_tinIssuingCountry: 'dgDec_tinIssuingCountry',

  //Nominee Details
  dgDec_communicationAL1: 'dgDec_communicationAL1',
  dgDec_communicationAL2: 'dgDec_communicationAL2',
  dgDec_communicationAL3: 'dgDec_communicationAL3',
  dgDec_landMark: 'dgDec_landMark',
  dgDec_city: 'dgDec_city',
  dgDec_district: 'dgDec_district',
  dgDec_pincode: 'dgDec_pincode',
  dgDec_state: 'dgDec_state',
  dgDec_country: 'dgDec_country',
  dgDec_communicationAL11: 'dgDec_communicationAL11',
  dgDec_communicationAL22: 'dgDec_communicationAL22',
  dgDec_communicationAL33: 'dgDec_communicationAL33',
  dgDec_city1: 'dgDec_city1',
  dgDec_district1: 'dgDec_district1',
  dgDec_pincode1: 'dgDec_pincode1',
  dgDec_state1: 'dgDec_state1',
  dgDec_country1: 'dgDec_country1',
  dgDec_Guardian_FN: 'dgDec_Guardian_FN',
  dgDec_Guardian_MN: 'dgDec_Guardian_MN',
  dgDec_Guardian_LN: 'dgDec_Guardian_LN',
  dgDec_Guardian_AL1: 'dgDec_Guardian_AL1',
  dgDec_Guardian_AL2: 'dgDec_Guardian_AL2',
  dgDec_Guardian_AL3: 'dgDec_Guardian_AL3',
  dgDec_Guardian_Landmark: 'dgDec_Guardian_Landmark',
  dgDec_Guardian_district: 'dgDec_guardian_district',
  dgDec_Guardian_city: 'dgDec_guardian_city',
  dgDec_Guardian_state: 'dgDec_guardian_state',
  dgDec_Guardian_pincode: 'dgDec_guardian_pincode',
  dgDec_Guardian_country: 'dgDec_guardian_country',
  dgDec_Nominee_Name: 'dgDec_Nominee_Name',
  dgDec_Nominee_FN: 'dgDec_Nominee_FN',
  dgDec_Nominee_MN: 'dgDec_Nominee_MN',
  dgDec_Nominee_LN: 'dgDec_Nominee_LN',
  dgDec_Nominee_FN_Label: 'dgDec_Nominee_FN_Label',
  dgDec_Nominee_RS_Label: 'dgDec_Nominee_RS_Label',
  dgDec_Nominee_DOB: 'dgDec_Nominee_DOB',
  dgDec_Nominee_On_Account_Yes: 'dgDec_Nominee_On_Account_Yes',
  dgDec_Nominee_On_Account_No: 'dgDec_Nominee_On_Account_No',
  dgDec_NomineeAddr_SameAs_Proprietor_Yes:
    'dgDec_NomineeAddr_SameAs_Proprietor_Yes',
  dgDec_NomineeAddr_SameAs_Proprietor_No:
    'dgDec_NomineeAddr_SameAs_Proprietor_No',
  dgDec_GuardianAddr_SameAs_Nominee_Yes:
    'dgDec_GuardianAddr_SameAs_Nominee_Yes',
  dgDec_GuardianAddr_SameAs_Nominee_No: 'dgDec_GuardianAddr_SameAs_Nominee_No',

  //GST Annexure
  dgDec_GSTAnnexure: 'dgDec_GSTAnnexure',
  dgDec_Name_Of_State: 'dgDec_Name_Of_State',
  dgDec_Name_Of_State_else: 'dgDec_Name_Of_State_else',
  dgDec_GST_Reg_No: 'dgDec_GST_Reg_No',
  dgDec_GST_Reg_No_else: 'dgDec_GST_Reg_No_else',
  dgDec_Add_As_GSTN_Rec: 'dgDec_Add_As_GSTN_Rec',
  dgDec_AddressLine1: 'dgDec_AddressLine1',
  dgDec_AddressLine1_else: 'dgDec_AddressLine1_else',
  dgDec_AddressLine2: 'dgDec_AddressLine2',
  dgDec_AddressLine2_else: 'dgDec_AddressLine2_else',
  dgDec_AddressLine3: 'dgDec_AddressLine3',
  dgDec_AddressLine3_else: 'dgDec_AddressLine3_else',

  // Credit facility declaration
  dgDec_bankName: 'dgDec_bankName',
  dgDec_branchName: 'dgDec_branchName',
  dgDec_facilityType: 'dgDec_facilityType',
  dgDec_accountNumber: 'dgDec_accountNumber',
  dgDec_sanctionedAmount: 'dgDec_sanctionedAmount',
  dgDec_submitButton: 'dgDec_submitButton',
  dgDec_radioOption1: 'dgDec_radioOption1',
  dgDec_radioOption2: 'dgDec_radioOption2',
  dgDec_radioOption3: 'dgDec_radioOption3',
  dgDec_radioOption4: 'dgDec_radioOption4',
  dgDec_radioOption5: 'dgDec_radioOption5',
  CreditFacilityOption1: 'CreditFacilityOption1',
  CreditFacilityOption2: 'CreditFacilityOption2',
  CreditFacilityOption3: 'CreditFacilityOption3',
  CreditFacilityOption4: 'CreditFacilityOption4',
  CreditFacilityOption5: 'CreditFacilityOption5',

  //Aadhar Declaration

  // Review Business details
  buss_entityName: 'bussEntityName',
  buss_accName: 'bussAccName',
  buss_lineOfBusiness: 'bussLineOfBusiness',
  buss_natureOfIndustry: 'bussNatureOfIndustry',
  buss_dateOfIncorp: 'bussDateOfIncorp',
  buss_annualTurnOvr: 'bussAnnualTurnOvr',
  buss_PEP: 'buss_PEP',
  buss_addr: 'buss_Addr',
  buss_mob: 'buss_Mob',
  buss_commAddr: 'bussCommAddr',
  buss_commMob: 'bussCommMob',

  // Review Proprietor details
  review_edit_btn: 'review_edit_btn',
  rw_pro_Declaration: 'rwProDeclaration',
  rw_pro_FullName: 'rwProFullName',
  rw_pro_gender: 'rwProGender',
  rw_pro_maritalStatus: 'rwProMaritalStatus',
  rw_pro_dob: 'rwProDob',
  rw_pro_cob: 'rwProCob',
  rw_pro_residentialStatus: 'rwProResidentialStatus',
  rw_pro_tinCountry: 'rwProTinCountry',
  rw_pro_countryOfTax: 'rwProCountryOfTax',
  rw_pro_PEP: 'rwProPEP',
  rw_pro_Mob: 'rwProMob',
  rw_pro_Email: 'rwProEmail',

  // Review Product Selection
  rw_prods_currAccVarient: 'rwProdsCurrAccVarient',
  rw_prods_internetBanking: 'rwProdsInternetBanking',
  rw_prods_stmtViaEmail: 'rwProdsStmtViaEmail',
  rw_prods_stmtFrequency: 'rwProdsStmtFrequency',
  rw_prods_offerRelatedSMS: 'rwProdsOfferRelatedSMS',
  rw_prods_chkBook: 'rwProdsChkBook',
  rw_prods_availDebit: 'rwProdsAvailDebit',
  rw_prods_branchName: 'rwProdsBranchName',
  rw_prods_doorStepbanking: 'rwProdsDoorStepbanking',
  rw_prods_frequency: 'rwProdsFrequency',

  //Journey Selection
  NoDigiLockerCard: 'noDigiCard',
  DigiLockerCard: 'digiLockerCard',
  DigiLockerGreenImage: 'digiLockerGreenImg',
  DigiLockerImage: 'digiLockerImg',
  DigiLocketTitle: 'digiLockerTitle',
  DigiLockerDescription: 'digiLockerDesc',
  DigiLockerButton: 'digiLockerButton',
  NoDigiImage: 'noDigiImg',
  NoDigiDecription: 'noDigiDesc',
  NoDigiButton: 'noDigiButton',
  NoDigiTitle: 'noDigiTitle',

  // Promotion No Offers
  IDFC_Logo: 'IDFC_logo',
  StartButton: 'startButton',
  LearnMore1: 'LearnMore1',
  LearnMore2: 'LearnMore2',
  LearnMore3: 'LearnMore3',

  //Create Lead
  cl_mobile_no: 'clMobileNumber',
  cl_pan_no: 'clPanNumber',
  cl_last_name: 'clLastName',
  cl_middle_name: 'clMiddleName',
  cl_first_name: 'clFirstName',
  cl_submit_button: 'clSubmitButton',
  cl_sole_properitor: 'clSoleProperiotor',

  //DashBoard
  NewJourneyButton: 'newJourneyButton',
  DB_Pending: 'DBPending',
  DB_InProgress: 'DB_InProgress',
  DB_Rework: 'DB_Rework',
  DB_Rejected: 'DB_Rejected',
  DB_AccountOpen: 'DB_AccountOpen',
  DB_AllItem: 'DB_AllItem',
  DB_AccessToken: 'DB_AccessToken',

  // Swipper
  SW_Previous: 'SW_Previous',
  SW_PageChange: 'SW_PageChange',
  SW_OnNext: 'SW_OnNext',
  SW_PageNumber: 'SW_PageNumber',

  //Knowledge Sharing
  KS_NextButton: 'KS_NextButton',
  KS_CloseAction: 'KS_CloseAction',

  //CAVariant Product feature Selection
  ca_variantDropdown: 'caVariantDropdown',
  ca_variantAdvPanel: 'caVariantAdvPanel',
  ca_featureFlatList: 'caFeatureFlatList',
  ca_proceedButton: 'caProceedButton',
  product_branchDropdown: 'productbranchDropdown',
  product_variantDropdown: 'productVariantDropdown',
  product_featureFlatList: 'productFeatureFlatList',

  product_internetBankingYesRadio: 'productInternetBankingYesRadio',
  product_internetBankingNoRadio: 'productInternetBankingNoRadio',
  product_smsOfferYesRadio: 'productSMSOfferYesRadio',
  product_smsOfferNoRadio: 'productSMSOfferNoRadio',
  product_emailStatementYesRadio: 'productEmailStatementYesRadio',
  product_emailStatementNoRadio: 'productEmailStatementNoRadio',

  product_sfDailyRadio: 'productSfDailyRadio',
  product_sfWeeklyRadio: 'productSfWeeklyRadio',
  product_sfFourthnightlyRadio: 'productSffourthnightlyRadio',
  product_sfMonthlyRadio: 'productSfMonthlyRadio',

  product_chequeBook25Radio: 'productchequeBook25Radio',
  product_chequeBook50Radio: 'productchequeBook50Radio',
  product_chequeBookNoRadio: 'productchequeBookNoRadio',
  product_ATMYesRadio: 'productATMYesRadio',
  product_ATMNoRadio: 'productATMNoRadio',
  product_DSYesRadio: 'productDSYesRadio',
  product_DSNoRadio: 'productDSNoRadio',
  product_DSFreAdHocRadio: 'productDSFreAdHocRadio',
  product_DSFreBeatRadio: 'productDSFreBeatRadio',

  product_FNLastName: 'productFNLastName',
  product_LNFirstName: 'productLNFirstName',
  product_IFNLastName: 'productIFNLastName',
  product_ILNFirstName: 'productILNFirstName',
  product_LNIFirstName: 'productLNIFirstName',
  product_FNILastName: 'productFNILastName',
  product_contactPerson: 'productContactPerson',
  product_mobile: 'productMobile',
  product_location: 'productLocation',
  product_proceedButton: 'productProceedButton',

  //Entity and AddressProof
  EA_documentType: 'entityDocType',
  EA_bills: 'billsType',
  EA_bankName: 'EAbankName',
  EA_idNumberAddressProof: 'EAidNumberAddressProof',
  uploadAddressProofDoc: 'uploadAddressProofDoc',
  idNumberAddressProof: 'idNumberAddressProof',
  EA_proceedBtn: 'EAProceedButton',
  EA_idNumberEntity: 'idNumberEntity',
  idNumber_AddresProof: 'dNumberAndAddresProof',
  EA_dlno: 'dlnoEntity',
  EA_Voter: 'voterIdEntity',
  EA_passportEntity: 'passportEntity',
  idNumberCommunication: 'idNumberCommunication',
  EA_fileNumber: 'EAfFileNumber',
  EA_rentDOB: 'EARentDOB',
  EA_expiryDate: 'EAExpiryDate',
  EA_DOB: 'EADobForCommunicationAddress',
  EA_expire: 'EAexpire',
  EA_DOBCommunication: 'EADobForCommunication',
  EA_passportExpire: 'EAPassportExpire',
  EA_entityIdentityProof: 'EAEntityIdentityProof',
  EA_bsPassword: 'EABsPassword',
  EA_communication: 'EA_Communication',
  EA_radioYes: 'EARadioYes',
  EA_radioNo: 'EARadioNo',
  EA_radioNotarised: 'EARadioNotarised',
  EA_radioRegister: 'EARadioRegister',

  //Pan Details
  pan: 'pan',
  pan_HolderName: 'panHolderName',
  pan_RetryButton: 'retryButton',
  pan_DocType: 'panDocType',
  pan_Aadhar: 'panAadhar',
  pan_DL: 'DLFormField',
  pan_Voter: 'voterFormField',
  pan_Passport: 'passportFormField',
  pan_DOB: 'panDOB',
  pan_Expiry: 'panExpiryDate',
  pan_FileName: 'panFileName',
  pan_ProceedBtn: 'panProceedBtn',

  //Add Proprietor Details
  pro_salutation: 'proSalutation',
  pro_firstName: 'proFirstName',
  pro_middleName: 'proMiddleName',
  pro_lastName: 'propLastName',
  pro_DOB: 'proDOB',
  pro_gender: 'proGender',
  pro_fatherName: 'proFatherName',
  pro_motherName: 'proMotherName',
  pro_maidenName: 'proMaidenName',
  pro_nationality: 'proNationality',
  pro_countryOfBirth: 'proCountryOfBirth',
  pro_countryOfTax: 'proCountryOfTax',
  pro_dmob: 'proDmob',
  pro_yob: 'proYob',
  pro_genderDropDown: 'proGenderDropDown',
  pro_father: 'proFather',
  pro_mother: 'proMother',
  pro_nation: 'proNation',
  pro_countryDOB: 'proCountryDOB',
  pro_countryTax: 'proCountry',
  pro_address1: 'proAddress1',
  pro_address2: 'proAddress2',
  pro_address3: 'proAddress3',
  pro_landmark: 'proLandmark',
  pro_city: 'proCity',
  pro_district: 'proDistrict',
  pro_pincode: 'proPincode',
  pro_state: 'proState',
  pro_country: 'proCountry',
  pro_mobile: 'proMobile',
  pro_landline: 'proLandline',
  pro_email: 'proEmail',
  pro_camera: 'proCamera',
  pro_proceed: 'proProceed',

  //review Nominee Details
  rw_nomi_name: 'rwNomiName',
  rw_nomi_relation: 'rwNomirelation',
  rw_nomi_dob: 'rwNomirelation',
  rw_nomi_fatherName: 'rwNomifatherName',
  rw_nomi_nameOnAcc: 'rwNominameOnAcc',
  rw_gst_name: 'rwGstname',
  rw_gst_branchName: 'rwGstbranchName',
  rw_gst_status: 'rwGststatus',
  rw_gst_nameOfState: 'rwGstnameOfState',
  rw_gst_nameRegistrNo: 'rwGstnameRegistrNo',
  rw_gst_exempted: 'rwGstexempted',
  rw_gst_relatedToIDFC: 'rwGstrelatedToIDFC',
  rw_gst_remarks: 'rwGstremarks',
  rw_gst_addr: 'rwGstaddr',

  //Add Approval
  approval_document: 'approvalDocument',
  exception_document: 'exceptionDocument',

  //ETB AND NTB
  Agree_Proceed_Btn: 'AgreeProceedBtn',
  Disagree_Btn: 'Disagree',

  //SVR
  svr_sourceOfLead: 'svr_sourceOfLead',
  svr_mentionOtherSourceOpt: 'svr_mentionOtherSourceOpt',
  svr_pvtLtdPROBE: 'svr_pvtLtdPROBE',
  svr_natureOfBusiness: 'svr_natureOfBusiness',
  svr_nameOfCompanyInAbbreviation: 'svr_nameOfCompanyInAbbreviation',
  svr_matchingAbbreviation: 'svr_matchingAbbreviation',
  svr_easeOfLocatingSite: 'svr_easeOfLocatingSite',
  svr_physicalAppearanceBuilding: 'svr_physicalAppearanceBuilding',
  svr_addressLocality: 'svr_addressLocality',
  svr_mentionAddressLocality: 'svr_mentionAddressLocality',
  svr_typeOfOffice: 'svr_typeOfOffice',
  svr_natureOfOwnershipAddress: 'svr_natureOfOwnershipAddress',
  svr_entityDirectorOpt: 'svr_entityDirectorOpt',
  svr_yearsOperatingAddress: 'svr_yearsOperatingAddress',
  svr_operatedMultipleLocations: 'svr_operatedMultipleLocations',
  svr_reasonMultipleOpt: 'svr_reasonMultipleOpt',
  svr_numberOfSuchAddresses: 'svr_numberOfSuchAddresses',
  svr_reasonDifferentCommAddressOpt: 'svr_reasonDifferentCommAddressOpt',
  svr_productDealing: 'svr_productDealing',
  svr_IDFCFIRSTBankCustomerID: 'svr_IDFCFIRSTBankCustomerID',
  svr_detailsOfRelationship: 'svr_detailsOfRelationship',
  svr_affiliationsMembership: 'svr_affiliationsMembership',
  svr_companyAbbreviationYes: 'svr_companyAbbreviationYes',
  svr_companyAbbreviationNo: 'svr_companyAbbreviationNo',
  svr_easeOfLocatingSiteEasy: 'svr_easeOfLocatingSiteEasy',
  svr_easeOfLocatingSiteDifficult: 'svr_easeOfLocatingSiteDifficult',
  svr_easeOfLocatingSiteUntraceable: 'svr_easeOfLocatingSiteUntraceable',
  svr_physicalAppearanceBuildingExcellent:
    'svr_physicalAppearanceBuildingExcellent',
  svr_physicalAppearanceBuildingGood: 'svr_physicalAppearanceBuildingGood',
  svr_physicalAppearanceBuildingPoor: 'svr_physicalAppearanceBuildingPoor',
  svr_natureOfOwnershipOfAddressOwend: 'svr_natureOfOwnershipOfAddressOwend',
  svr_natureOfOwnershipOfAddressRented: 'svr_natureOfOwnershipOfAddressRented',
  svr_natureOfOwnershipOfAddressPG: 'svr_natureOfOwnershipOfAddressPG',
  svr_doesCustomerFromMultiLocYes: 'svr_doesCustomerFromMultiLocYes',
  svr_doesCustomerFromMultiLocNo: 'svr_doesCustomerFromMultiLocNo',
  svr_isMoreThanCompanyFromSameAddrYes: 'svr_isMoreThanCompanyFromSameAddrYes',
  svr_isMoreThanCompanyFromSameAddrNo: 'svr_isMoreThanCompanyFromSameAddrNo',
  svr_reasonMoreThanOneCompanyOpt: 'svr_reasonMoreThanOneCompanyOpt',
  svr_workingEmployeeSeen: 'svr_workingEmployeeSeen',

  svr_ReasonDifferentCommAddressReqComm:
    'svr_ReasonDifferentCommAddressReqComm',
  svr_easeOfLocatingSiteEasyComm: 'svr_easeOfLocatingSiteEasyComm',
  svr_easeOfLocatingSiteDifficultComm: 'svr_easeOfLocatingSiteDifficultComm',
  svr_easeOfLocatingSiteUntraceableComm:
    'svr_easeOfLocatingSiteUntraceableComm',
  svr_physicalAppearanceBuildingExcellentComm:
    'svr_physicalAppearanceBuildingExcellentComm',
  svr_physicalAppearanceBuildingGoodComm:
    'svr_physicalAppearanceBuildingGoodComm',
  svr_physicalAppearanceBuildingPoorComm:
    'svr_physicalAppearanceBuildingPoorComm',
  svr_natureOfOwnershipOfAddressOwendComm:
    'svr_natureOfOwnershipOfAddressOwendComm',
  svr_natureOfOwnershipOfAddressRentedComm:
    'svr_natureOfOwnershipOfAddressRentedComm',
  svr_natureOfOwnershipOfAddressPGComm: 'svr_natureOfOwnershipOfAddressPGComm',
  svr_yearsOperatingAddressComm: 'svr_yearsOperatingAddressComm',
  svr_inCaseOfResidencyDirectorYes: 'svr_inCaseOfResidencyDirectorYes',
  svr_inCaseOfResidencyDirectorNo: 'svr_inCaseOfResidencyDirectorNo',
  svr_isMoreThanCompanyFromSameAddrCommYes:
    'svr_isMoreThanCompanyFromSameAddrCommYes',
  svr_isMoreThanCompanyFromSameAddrCommNo:
    'svr_isMoreThanCompanyFromSameAddrCommNo',
  svr_reasonMoreThanOneCompanyCommOpt: 'svr_reasonMoreThanOneCompanyCommOpt',
  svr_typeOfSinage: 'svr_typeOfSinageList',
  svr_designationDM: 'svr_designationDM',
  svr_nameDM: 'svr_nameDM',
  svr_nameSignature: 'svr_nameSignature',
  svr_ageSignature: 'svr_ageSignature',
  svr_holdingPositionSignature: 'svr_holdingPositionSignature',
  svr_noOfYearsExperienceSignature: 'svr_noOfYearsExperienceSignature',
  svr_makerNameRecommendation: 'svr_makerNameRecommendation',
  svr_designationRecommendation: 'svr_designationRecommendation',
  svr_employeeCodeRecommendation: 'svr_employeeCodeRecommendation',
  svr_selectDateRecommendation: 'svr_selectDateRecommendation',
  svr_commentRecommendation: 'svr_commentRecommendation',
  svr_checkerNameRecommendation: 'svr_checkerNameRecommendation',
  svr_designationRecommendationSecond: 'svr_designationRecommendationSecond',
  svr_officeIsRented: 'svr_officeIsRented',
  svr_nameOfAbbreviation: 'svr_nameOfAbbreviation',
  svr_boardNotSeen: 'svr_boardNotSeen',
  svr_businessActivitySeen: 'svr_businessActivitySeen',
  svr_detailedFeedbackNeighbour: 'svr_detailedFeedbackNeighbour',
  svr_natureOfAbbreviationUsed: 'svr_natureOfAbbreviationUsed',
  svr_PleaseUploadCustomerSignatureOne: 'svr_PleaseUploadCustomerSignatureOne',
  svr_PleaseReUploadCustomerSignatureOne:
    'svr_PleaseReUploadCustomerSignatureOne',
  svr_PleaseUploadCustomerSignatureTwo: 'svr_PleaseUploadCustomerSignatureTwo',
  svr_PleaseReUploadCustomerSignatureTwo:
    'svr_PleaseReUploadCustomerSignatureTwo',
  svr_entityInfo_saveDraft: 'svr_entityInfo_saveDraft',
  svr_AddVerRep_saveDraft: 'svr_AddVerRep_saveDraft',
  svr_MakerChecker_saveDraft: 'svr_MakerChecker_saveDraft',
  svr_BusinessInfo_saveDraft: 'svr_BusinessInfo_saveDraft',
  svr_DecisionMaker_saveDraft: 'svr_DecisionMaker_saveDraft',
  svr_proceedButton: 'svr_proceedButton',
  svr_dummyNavButton: 'svr_dummyNavButton',
  svr_eca_tickmark_image: 'svr_eca_tickmark_image',
  svr_eca_done_image: 'svr_eca_done_image',

  //UploadDoc
  ud_tap: 'uploadDoc',
  ud_image: 'ud_image',
  ud_preview: 'ud_preview',
  ud_uploadImage: 'ud_uploadImage',
  ud_downloadImage: 'ud_download',

  //CustomModalDropDown
  cd_onSelect: 'onSelet',

  // Pop Ups
  icnPopUp: 'icnPopUp',
  titlePopUp: 'titlePopUp',
  icnSuccess: 'successImg',
  icnError: 'errorImg',
  popOk: 'pop_ok',
  popCancel: 'pop_cancel',

  pop_term_agree: 'pop_term_agree',
  pop_suc_next: 'pop_suc_next',
  pop_err_next: 'pop_err_next',
  pop_otp_verify: 'pop_otp_verify',
  pop_otp_resend: 'pop_otp_resend',
  pop_thank_proceed: 'pop_thank_proceed',
  pop_pdrop_proceed: 'pop_pdrop_proceed',
  pop_bureauFail_proceed: 'pop_bureauFail_proceed',
  pop_bureauPass_proceed: 'pop_bureauPass_proceed',
  pop_creditCheck_proceed: 'pop_creditCheck_proceed',

  // Mobile dedupe
  pop_dedupe_proceed: 'pop_dedupe_proceed',
  selectReason: 'selectReason',

  // Mismatch Fields
  mn_uploadDoc: 'mnUploadDoc',
  mismatchTitle: 'mismatchTitle',
  pop_mismatch_proceed: 'pop_mismatch_proceed',
  pop_matchName: 'pop_matchName',
  pop_matchNameList: 'pop_matchNameList',
  pop_matchNameProof: 'pop_matchNameProof',
  pop_matchNameProofList: 'pop_matchNameProofList',
  pop_matchName_proceed: 'pop_matchName_proceed',
  pop_matchName_back: 'pop_matchName_back',
  pop_matchName_uploadDoc: 'pop_matchName_uploadDoc',

  // Journey Complete
  pop_journey_detail: 'pop_journey_detail',
  pop_journey_description: 'pop_journey_description',
  pop_journey_caseRefID: 'pop_journey_caseRefID',
  pop_journey_proceed: 'pop_journey_proceed',

  // Funding Cheque
  pop_fund_detail: 'pop_fund_detail',
  pop_fund_proceed: 'pop_fund_proceed',

  // Choice Account Number
  can_customize_account_number: 'can_customize_account_number',
  can_anywhere: 'can_anywhere',
  can_start_with: 'can_start_with',
  can_end_with: 'can_end_with',
  can_check_availability: 'can_check_availability',
  can_proceedButton: 'can_proceedButton',
  can_dummyNavButton: 'can_dummyNavButton',
};

export const StateMachineStages = {
  INITIAL: 'INITIAL',
  LEAD_REFID_DONE: 'LEAD_REFID_DONE',
  PROPRIETOR_KYC_DONE: 'PROPRIETOR_KYC_DONE',
  ENTITY_KYC_DONE: 'ENTITY_KYC_DONE',
  ENTITY_DETAILS_DONE: 'ENTITY_DETAILS_DONE',
  PROPRIETOR_DETAILS_DONE: 'PROPRIETOR_DETAILS_DONE',
  PRODUCT_SELECTION_DONE: 'PRODUCT_SELECTION_DONE',
  NOMINATIONS_DONE: 'NOMINATIONS_DONE',
  REVIEW_DONE: 'REVIEW_DONE',
  MITC_DONE: 'MITC_DONE',
  INITIALS_FUNDING_DONE: 'INITIALS_FUNDING_DONE',
  CROSS_OFFERS_DONE: 'CROSS_OFFERS_DONE',
  SVR_DONE: 'SVR_DONE',
  CASE_SUBMITTED: 'CASE_SUBMITTED',
};
