// Managed by vimita.hirpara_per
const passCap = 'Password';
const Try_Sometime = 'Please try after sometime.';
const System_Error = 'System Error';
const No_Network = 'Please check your internet connection.';
const Back = 'Back';
const Ok = 'OK';

export const LABELS = {
  BOLogin: {
    userName: 'UserName',
    password: passCap,
  },
  CreateLead: {
    businessType: 'businessType',
    firstName: 'First Name',
    lastName: 'Last Name',
    middleName: 'Middle Name (Optional)',
    mobileNumber: 'Mobile Number',
    pan: 'PAN',
  },
  PANDetails: {
    pan: 'PAN Details',
    panHolderName: "PAN Holder's Name",
    docType: 'Document Type',
    Driving_Lic_No: 'Driving License Number',
    Date_Birth: 'Date of Birth',
    Doc_Exp_Date: 'Document Expiry Date',
    Voter_ID_Number: 'Voter ID Number',
    Passport_Number: 'Passport Number',
    Passport_File_Number: 'File Number',
    Aadhar_Number: 'Aadhar Number',
    uidText: '12 Digit UID',
  },
  EntityAddressProof: {
    docTypeEntity: 'Document Type',
    idNumberEntity: 'ID Number',
    idNumberCommunicationDL: 'Driving License Number',
    idNumberCommunicationV: 'Voter ID Number',
    idNumberCommunicationP: 'Passport Number',
    Date_Birth: 'Date of Birth',
    Doc_Exp_Date: 'Document Expiry Date',
    Driving_Lic_No: 'Driving License Number',
    Passport_Number: 'Passport Number',
    Voter_ID_Number: 'Voter ID Number',
    docType: 'Document Type',
    bankName: 'Bank Name',
    Passport_File_Number: 'File Number',
    Date_Of_Agreement: 'Date Of Agreement',
    Document_Expiry_Date: 'Document Expiry Date',
    Bank_Account_Number: 'Bank Account Number',
    Bank_Account_Password: 'Enter Password',
    Account_Number: 'Account Number',
    IFSC_Code: 'IFSC Code',
    Bank_Statement_Date: 'Bank Statement Start Date',
    Bank_Statement_End_Date: 'Bank Statement End Date',
    Aadhar_Number: 'Aadhar Number',
    uidText: '12 Digit UID',
  },
  AddBusinessDetails: {
    entityName: 'Entity Name',
    accountTitle: 'Account Title',
    iECCodeOptional: 'IEC Code (Optional)',
    iECCodeRequired: 'IEC Code',
    websiteOptional: 'Website (Optional)',
    bussAddressLine1: 'Business Address Line 1',
    bussAddressLine2: 'Business Address Line 2',
    bussAddressLine3: 'Business Address Line 3',
    landmarkOpt: 'Landmark (Optional)',
    cityBal: 'City',
    districtBal: 'District',
    pinCodeBal: 'Pincode',
    stateBal: 'State',
    countryBal: 'Country',
    mobileBal: 'Mobile',
    landlineOptional: 'Landline (Optional)',
    emailBal: 'Email',
    communicationAL1: 'Communication Address Line 1',
    communicationAL2: 'Communication Address Line 2',
    communicationAL3: 'Communication Address Line 3',
    landmarkOptCAL: 'Landmark (Optional)',
    cityCAL: 'City',
    districtCAL: 'District',
    pincodeCAL: 'Pincode',
    stateCAL: 'State',
    countryCAL: 'Country',
    mobileCAL: 'Mobile',
    landlineCAL: 'Landline (Optional)',
    emailCAL: 'Email',
    lineOfBusiness: 'Line of. Business',
    natureOfIndustry: 'Nature of Industry',
    annualTurnover: 'Annual Turnover',
    internationalTradeTurnover: 'internationalTradeTurnover',
    IECCode: 'IEC Code',
    PEP: 'PEP',
    dateOfIncorporation: 'Date of Incorporation',
    businessAddress: 'Business Address',
    businessMobileNum: 'Business Mobile Number',
    businessLandlineNum: 'Business Landline Number',
    communicationAddress: 'Communication Address',
    comMobNum: 'Communication Mobile Number',
    comLandlineNum: 'Communication Landline Number',
  },
  AddProprietorDetails: {
    salutation: 'Salutation',
    firstName: 'First Name',
    middleName: 'Middle Name (Optional)',
    lastName: 'Last Name',
    dob: 'Date of Birth',
    yob: 'Year of Birth',
    dmob: 'Date and Month of Birth',
    gender: 'Gender',
    fatherName: "Father's Name",
    motherName: "Mother's Name",
    mothersMaidenName: 'Mother’s Maiden Name',
    nationality: 'Nationality',
    countryOfBirth: 'Country of Birth',
    countryOfTax: 'Country of TAX Residency',
    address1: 'Proprietor Address Line 1',
    address2: 'Proprietor Address Line 2',
    address3: 'Proprietor Address Line 3',
    landmark: 'Landmark (Optional)',
    city: 'City',
    district: 'District',
    pincode: 'Pincode',
    state: 'State',
    country: 'Country',
    mobile: 'Mobile',
    landline: 'Landline (Optional)',
    email: 'Email',
    //added from review screen
    landlineNumber: 'Landline Number',
    mobileNumber: 'Mobile Number',
    address: 'Address',
    PEP: 'PEP',
    maidenName: 'Maiden Name',
    proprietorFullName: 'Proprietor Full Name',
  },
  AddInitialFunds: {
    chequeNumber: 'Cheque Number',
    chequeDate: 'Cheque Date',
    ifscCode: 'IFSC Code',
    branchName: 'Branch Name',
    bankName: 'Bank Name',
    fundingAmount: 'Enter funding amount*',
  },
  ProductSelection: {
    contactPerson: 'Contact Person',
    location: 'Location',
    mobile: 'Mobile',
    branchName: 'Branch Name',
  },
  ProprietorDeclaration: {
    ProprietorsName: 'Proprietors Name',
    FathersName: 'Fathers Name',
    MaidenName: 'Maiden Name (If any)',
    MothersName: 'Mothers Name',
    MaritalStatus: 'Marital Status',
    ResidentialStatus: 'Residential Status',
    ProprietorsDateofBirth: 'Proprietors Date of Birth',
    CountryofBirth: 'Country of Birth',
    CountryofTaxResidency: 'Country of Tax Residency',
    TINIssueingCountry: 'TIN Issueing Country',
    nationality: 'Nationality',
  },
  NomineeDetails: {
    nomineesName: 'Nominees Name',
    relationCustomer: 'Relationship with Customer',
    nomineesDob: "Nominee's Date of Birth",
    fathersName: 'Fathers Name',
    guardiansName: 'Guardians Name',
    mentionNomineeNameOnAcc: 'Mention Nominee Name on Ac statements/advices',
    nomineeAddr: 'Nominee Address',
    guardianAddr: 'Guardian Address',
  },
  GSTDetails: {
    customerName: 'Customer Name',
    branchName: 'Branch Name',
    GSTStatus: 'GST Status',
    nameOfState: 'Name of the State',
    GSTRegistrationNum: 'GST Registration Number',
    exemptedFrmGST: 'Exempted from GST',
    relatedPersonToIDFC: 'Related person to IDFC FIRST Bank',
    remarks: 'Remarks',
    GSTAddr: 'Address as per GSTN records',
  },
  CreditFacilityDeclaration: {
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    facilityType: 'Facility Type',
    accountNumber: 'Account Number',
    sanctionAmount: 'Sanction Amount',
  },
  BankUse: {
    leadID: 'Lead ID',
    variantName: 'Variant Name',
    variantCode: 'Variant Code',
    leadConverter: 'Lead Converter',
    leadGenerator: 'Lead Generator (Optional)',
    leadwarmer: 'Lead Warmer (Optional)',
    promoCode: 'Promo Code (Optional)',
    campaignCode: 'Campaign Code (Optional)',
    exceptionDoc: 'Select Exception Document',
    approval: 'Approvar',
  },
  SiteVerificationReport: {
    SourceOfLead: 'Source of Lead',
    MentionOtherSourceOpt: 'Mention Other Source of Lead (Optional)',
    MentionOtherSourceReq: 'Mention Other Source of Lead',
    PvtLtdPROBE: 'Pvt.Ltd & Validated PROBE & SARVA',
    NatureOfBusiness: 'Nature of Business',
    NameOfCompanyInAbbreviation: 'Name of the Company in Abbreviation',
    MatchingAbbreviationReq: 'Matching Abbreviation on Google Search',
    MatchingAbbreviationOpt:
      'Matching Abbreviation on Google Search (Optional)',
    EaseOfLocatingSite: 'Ease of Locating Site',
    PhysicalAppearanceBuilding: 'Physical Appearance of the Building',
    AddressLocality: 'Address Locality',
    MentionAddressLocalityOpt: 'Mention Other Address Locality (Optional)',
    MentionAddressLocalityReq: 'Mention Other Address Locality',
    TypeOfOffice: 'Type of Office',
    NatureOfOwnershipAddress: 'Nature of Ownership Address',
    EntityDirectorOpt: 'Entity is Director/Trustee/Promoter (Optional)',
    YearsOperatingAddress: 'Years of Operating From This Address',
    OperatedMultipleLocations: 'Operated from Multiple Locations',
    ReasonMultipleOpt: 'Reason of Multiple Locations (Optional)',
    ReasonMultipleReq: 'Reason of Multiple Locations',
    NumberOfSuchAddresses: 'Number of Such Addresses',
    ReasonDifferentCommAddressOpt:
      'Reason of Different Communication Address (Optional)',
    ReasonDifferentCommAddressReq: 'Reason of Different Communication Address',
    Yes: 'Yes',
    No: 'No',
    Low: 'Low',
    High: 'High',
    Poor: 'Poor (no activity)',
    ProductDealing: 'Product Dealing in',
    IDFCFIRSTBankCustomerIDReq: 'IDFC FIRST Bank Customer ID',
    IDFCFIRSTBankCustomerIDOpt: 'IDFC FIRST Bank Customer ID (Optional)',
    DetailsOfRelationshipReq: 'Details of Relationship',
    DetailsOfRelationshipOpt: 'Details of Relationship (Optional)',
    AffiliationsMembership: 'Affliations/membership of associations',
    BusinessBoard:
      'Was the Business Board, Signage seen outside the Business Address?',
    MatchAccountTitle: 'Does the board match the account Title?',
    NeighboursAwareCustomerentity:
      'Were the neighbours (shops/office) aware of the customer/entity?',
    NatureAndLineOfBusiness:
      'Was the activity aligned with the nature & line of business?',
    NecessaryInfra:
      'Was the necessary infrastructure sighted in line with business activity?',
  },
};

export const ErrorPopUpTypes = {
  ok: {
    title: System_Error,
    message: Try_Sometime,
    actionName: Ok,
  },
  networkError: {
    title: 'Network Error',
    message: No_Network,
    actionName: Ok,
  },
  retry: {
    title: 'Retry',
    message: Try_Sometime,
    actionName: Ok,
  },
  uploadError: {
    title: 'Document Upload Error',
    message: Try_Sometime,
    actionName: Ok,
  },
  invalidPan: {
    title: 'Please enter valid PAN',
    message: 'Please check the PAN entered.',
    actionName: Back,
  },
  bsPanMismatch: {
    title: 'Mismatch found in PAN!',
    message: 'Please check the PAN entered.',
    actionName: Back,
    width: '50%',
    top: 70,
  },
  invalidDocVerify: {
    title: 'Cannot validate the document',
    message: 'please provide other document or Proceed with same document.',
    actionName: Ok,
  },
  aadharNoNotMatch: {
    title: 'Fingerprint does not match entered Aadhar.',
    message:
      'Make sure to provide correct fingerprint or update the Aadhar number.',
    actionName: Ok,
  },
  dlNotActive: {
    title: System_Error,
    message:
      'Oh-no! Your License validity has expired. Please provide another document to proceed.',
    actionName: Ok,
  },
  voterIdNotActive: {
    title: System_Error,
    message:
      'Oh-no! Your Voter ID is not active. Please provide another document to proceed.',
    actionName: Ok,
  },
  fileNumberNotActive: {
    title: System_Error,
    message:
      'Oh-no! The File Number you have entered is inactive.Please provide another document to proceed.',
    actionName: Ok,
  },
  aadharNotActive: {
    title: '',
    message:
      'Oh-no! Your AADHAAR number is not active. Provide another document to proceed.',
    actionName: Ok,
  },
  aadharApiFail: {
    title: System_Error,
    message: 'Please proceed with some other document.',
    actionName: Ok,
  },
  aadharDeviceNotConnect: {
    title: 'Biometric device not connected',
    message: 'Please check or proceed with another document.',
    actionName: Ok,
  },
  aadhaFringerprint: {
    title: 'Take fingerprint of the customer on the Biometric device.',
    message: '',
    actionName: Ok,
  },
  aadharBluetoothoff: {
    title: 'Bluetooth device not enable',
    message: 'Please is enable Bluetooth of device.',
    actionName: Ok,
  },
  aadharBluetoothPermission: {
    title: 'Bluetooth Permission',
    message: 'Please is enable Bluetooth Permission.',
    actionName: Ok,
  },
  bsAddressNotAvailable: {
    title: 'Entity Address is not available!',
    message: 'Unfortunately, entity address proof is not available.',
    subMessage1: ' Upload another document to proceed.',
    actionName: 'Select Other Entity Address Proof',
    width: '80%',
    top: 80,
  },
  bsbankNameMismatch: {
    title: 'Mismatch found in selected Bank Name and uploaded E-pdf!',
    message:
      "Uh-oh! Seems like there's a mismatch in your Bank name. Select the correct Bank name or upload correct E-PDF. ",
    actionName: Back,
    width: '50%',
    top: 60,
  },
  bsInvalidBankStatement: {
    title: 'Please upload the Bank Statement for 3 months!',
    message: 'Uh-oh! Your bank statement is of ',
    subMessage1: 'less than 3 months.',
    subMessage2: ' Please check and re-upload the correct document.',
    actionName: Back,
    width: '50%',
    top: 0,
  },
  bsAccountNotActivated: {
    title: 'Account not active!',
    actionName: 'Select Other Entity Address Proof',
    message:
      'Aw-snap! Account number in the Bank statement is not active. Proceed with ',
    subMessage1: ' another document type.',
    width: '80%',
    top: 60,
  },
  retryMasterData: {
    title: 'MasterData Failure',
    message:
      "Master data fetcing is failed, You can't proceed furthure. Please try again.",
    actionName: Back,
  },
};

export const Strings = {
  BtnTitles: {
    Back: 'Back',
    Submit: 'Submit',
    Proceed: 'Proceed',
    Preview: 'Preview',
    Reupload: 'Re-upload',
    Download: 'Download',
    Verify: 'Verify',
    Close: 'Close',
    Retry: 'Retry',
    selectAnotherDoc: 'Select Another Document',
    agreeAndProceed: 'Agree & Proceed',
    disagree: 'Disagree',
    Ok: 'OK',
    Cancel: 'Cancel',
    goToDashBoard: 'Agree, Go to Dashboard',
    provideDocument: 'Provide Documents',
    provideDeclaration: 'Provide Declaration',
    SubmitDeclaration: 'Submit Declaration',
    add: 'Add',
    SaveDraft: 'Save Draft',
    CheckAvailability: 'Check Availability',
    ShowOptions: 'Show Options',
    AcceptAndProceed: 'Accept & Proceed',
  },

  RadioButtonOptions: {
    yes: 'Yes',
    no: 'No',
  },

  AddressLabels: {
    communicationAL1: 'Communication Address Line 1',
    communicationAL2: 'Communication Address Line 2',
    communicationAL3: 'Communication Address Line 3',
    city: 'City',
    state: 'State',
    district: 'District',
    pincode: 'Pincode',
    country: 'Country',
  },

  AlertMessages: {
    Oopss: 'Oops!',
    Congratulations: 'Congratulations!',
    Loading_Text: 'Please wait...',
    System_Error: 'System Error',

    Try_Sometime: 'Please try after sometime.',
    Something_wrong: 'Something went wrong, please try after some time.',
    No_Network: 'Please check your Internet connection.',
    Wait: 'Please wait, we are processing details.',
    Visit_Soon: 'Work is under progress, we will back soon.',
    uploadAPI:
      'Uh-oh! Uploaded document is incorrect. Upload correct document and retry.',
    uploadIncorrectFormat:
      'Aw-snap! The file uploaded is in a different format. Upload files only in PDF, TIFF & JPG formats and retry. ',
    uploadCurrupted:
      'Uh-oh! Uploaded document is not clear. Upload correct document and retry.',
    uploadTooLarge:
      'Aw-snap! Uploaded file size is more than 10 MB. Upload file smaller than 10 MB and retry.',
  },

  CAProgressHeader: {
    //Step 1 :
    PAN_Title: "Proprietor's PAN Details, Identity and Address Proof",
    PAN_Sub_Title: "Please upload proprietor's PAN and OVD",
    EA_Title: 'Entity Identity and Address Proof',
    EA_Sub_Title:
      'Please provide documents to establish proof of identity and proof of address for your proprietor’s business',
    ABD_Title: 'Add Business Details',
    ABD_Sub_Title: 'Please provide basic details for proprietor’s business',
    APD_Title: 'Add Proprietor Details',
    APD_Sub_Title: 'Please complete basic details about the business owner',

    //Step 2 :
    Variant_Title: 'Product Variant and Feature Selection',
    Variant_Sub_Title:
      'Help your proprietor choose the Current Account best suited for their business',

    //Step 3 :
    NDD_Title: 'Nominee Details & Declarations',
    NDD_Sub_Title: 'Complete nominee details and provide declarations',
    Review_Title: 'Review Details',
    Review_Sub_Title: 'Almost there! Please review the details provided',
    CIF_Title: 'Customer Information Form',
    CIF_Sub_Title:
      'Please upload the Customer Information Form signed by your customer',

    //Step 4 :
    AIF_Title: 'Initial Funds',
    AIF_Sub_Title: 'Please help customer add funds to his current account',

    //Step 6 :
    BankUse_Title: 'Bank Use',
    BankUse_Sub_Title:
      'Please check the Lead Details, Bank Clarification and Approvals',

    // Step 5
    SVR_Title: 'Internal Procedures',
    SVR_Sub_Title:
      'Please proceed with site verification to complete the account creation process',

    // Step 7
    CAN_Title: 'Create Account Number',
    CAN_Sub_Title: "Choose an account number of your customer's preference",
  },

  BOLogin: {
    Title: 'IDFC Current Account',
    Username: 'Username',
    Password: 'Password',
  },
  PromotionNOffers: {
    Title: 'IDFC Current Account',
    Detail: 'Current account that cares for your customer in more than one way',
    Industry_First_Rewards: 'Industry First Rewards',
    Beyond_Banking_Offers: 'Beyond Banking Offers',
    businessFirst: 'Business First',
    Learn_More: 'Learn More',
  },
  CreateLead: {
    Title: 'Customer Details',
  },
  EtbNtbCheck: {
    Title: 'Existing Relationship Status',
    Section_1_Title: "Proprietor's Relationship with IDFC FIRST Bank",
    Section_2_Title: "Entity's Relationship",
    SubTitle:
      'Please provide details on your existing status with IDFC FIRST Bank',
    Section_1_SubTitle:
      'Existing relationship found with IDFC FIRST Bank with below mentioned details.',
    ProperiatorName: "Proprietor's Name",
    AccountNumber: 'Account Number',
    ProductType: 'Product Type',
    UCIC: 'UCIC',
    DormancyTitle: 'Dormancy Found in Account!',
    DormancyMessage: [
      'Uh-oh! seems like you are an existing customer of IDFC FIRST Bank, however, your account is in Dormant status. Activate your account to proceed further.',
    ],
    ReKYCTitle: 'Re-KYC is due!',
    ReKYCMessage: [
      // 'Re-KYC is due ',
      // 'within 90 days',
      // '. Please ',
      // 'provide documents for re-KYC ',
      // 'or provide KYC declaration if proceeding with the same KYC information.',
      'Uh-oh! seems like you are an existing customer of IDFC FIRST Bank and your Re-KYC is pending.Provide new documents for Re-KYC or KYC declaration to proceed with the existing KYC information.',
    ],
    ReKYCDeclaration: 'Re-KYC Declaration',
    FirstDeclaration:
      'I/We declare that there is no Politically Influenced Person (PEP) either as Director/Partner/Trustee/Office Bearer/Promoter/Authorized Signatory/Beneficial Owner in my/our organization.',
    SecondDeclaration:
      'I/We declare that one of our Directors/Partners/Trustees/Office Bearers/Promoters/Authorized Signatories/Beneficial Owners in my/our organization is Politically Influenced Person.',
    ThirdDeclaration:
      'I/We declare that there is no change in the status of Tax residency of any our Directors/Partners/Trustees/Office Bearers/Promoters (including proprietor)/Authorized Signatories/Beneficial Owners in my/our organization. There is no change in FACTA related information of the entity as per our last submission.',
    NoteForThirdDeclaration:
      '*In case of any change in FACTA related information, separate FACTA annexure is to be filled. (Annexure 2 and Annexure 3 or Annexure 4 as applicable)',
    FourthDeclaration:
      'I/We declare that there is no change in the line/nature of business or demographic details or beneficial owners or constitutional documents submitted/declared to the bank.',

    RoniEnrterprises: 'Roni Enterprises',
    RiniToyes: 'Rini Toyes',
    NewEntity: 'New Entity',
    Yes: 'Yes',
    No: 'No',
    SavingsAccount: 'Savings Account',
  },
  CAJourneySteps: {
    Text_1: 'Follow',
    Text_2: ' 5 ',
    Text_3: 'easy steps ',
    Text_4: 'to help your customer complete the application',
    Step_1_Title: 'KYC, Entity and Proprietor Details',
    Step_1_Detail:
      'Submit KYC documents and complete business & proprietor details for your customer',
    Step_2_Title: 'Product Selection',
    Step_2_Detail: 'Select from a wide range of Current Account products',
    Step_3_Title: 'Declaration & Review',
    Step_3_Detail: 'Provide declarations and review the application',
    Step_4_Title: 'Account & Offers',
    Step_4_Detail: 'Help customer explore a range of tailored offers',
    Step_5_Title: 'Internal Processes & Submission',
    Step_5_Detail: 'Complete internal procedures & submit the documents',
  },
  DocumentAuthType: {
    DigiLocker_Title: 'Provide documents via DIGI LOCKER',
    DigiLocker_Detail:
      'Simple steps for paperless account opening process. Authorize Digilocker to fetch documents.',
    btnDigiLocker: 'Proceed via DIGI LOCKER',

    Non_DigiLocker_Title: 'Scan and upload KYC Documents',
    Non_DigiLocker_Detail:
      'Help your customer provide Entity and Proprietor KYC documents.',
    btnNonDigiLocker: 'Proceed without DIGI LOCKER',
  },
  BODashboard: {
    Title: 'Dashboard',
    CreateLead: 'Initiate New Case',
    TotalCases: 'TOTAL CASES',
    PendingCases: 'My Pending',
    InProgress: 'In Progress',
    AccountOpen: 'Account Open',
    Rework: 'Rework',
    SentBy: 'Sent By',
    Rejected: 'Rejected',
    Overview: 'Overview',
    AllItems: 'All Items',
    Pending: 'Pending',
    Status: 'Status',
    SrNo: 'Sr No.',
    LeadId: 'Lead Id',
    EntityType: 'Entity Type',
    EntityName: 'Entity Name',
    CreatedOn: 'Created On',
    Stage: 'Stage',
    CustomerName: 'Customer Name',
    Dashboard: 'Dashboard',
    Welcome: 'Welcome',
    KnowledgeSharingText: 'Knowledge Sharing Repositories',
    Logout: 'Logout',
    ApprovarName: 'Prathamesh Sawant',
    Steps:
      'If above mentioned folder is not available then follow the below steps:',
    PopUpTitle: 'Refer Business Banking Folder',
    FirstStep: 'Approval required for access - ',
    SecondStep1: 'Post obtaining approval from ',
    SecondStep2_1: ' for',
    SecondStep2_2: ' Infinite vault',
    SecondStep2_3:
      ' >> business banking folder access kindly raise the ticket in I',
    SecondStep3: ' support/Service ',
    SecondStep4: 'Now under Infrastructure >> ID management request',
    Category: 'Category - Service request',
    SubCategory: 'Sub category -  Distribution List modification',
    ThirdStep1: 'Please attach the approval ',
    ThirdStep2: 'in the ticket ',
    ThirdStep3:
      'and Reporting Manager also need to approve the ticket in I support',
    PendingWith: 'Pending With',
    Remark: 'Remark',
    AccountNumber: 'Account No.',
    Bank: 'Bank',
    AccNumberTemp: '0000 00000',
  },

  // Step No : 1 Complete KYC -----------------------------------------
  PANDetails: {
    Section_1_Title: 'Proprietor’s PAN Details',
    Section_2_Title: 'Proprietor’s Identity and Address Proof',

    Doc_upload1: 'Please upload ',
    Doc_upload2: ' Document',

    Driving_Lic_No: 'Driving License Number',
    Date_Birth: 'Date of Birth',
    Doc_Exp_Date: 'Document Expiry Date',

    Proof_of_NC: 'Proof of Name Change',
    Name_Popup: 'Mismatch in Proprietor name found',
    Dob_Popup: 'Mismatch Found in Date of Birth!',
    Dob_Popup_desc:
      'Uh-oh! Seems like your Date of Birth is not the same across all your documents. Provide correct Date of Birth and retry.',
  },
  EntityAndAddress: {
    Section_1_Title: 'Select and upload document for Entity Identity Proof',
    Section_2_Title: 'Select and upload document for Entity Address proof',
    Communication_Address: 'Communication Address is same as Business Address',
    e_Pdf: 'E-pdf Uploaded',
    Bank_Statement1: 'Select a mode to submit your ',
    Bank_Statement2: 'last 3 months’',
    Bank_Statement3: ' bank statement digitally',
    Scan_Upload: 'Scan and Upload\nPhysical Bank Statement',
    Gst_Doc: 'Please upload GST Certificate',
    Shop_Cer: 'Please upload Shop & Establishment Certificate',
    Reg_Cer:
      'Please upload Registration Certificate issued by Excise & Customs Department',
    Proff_Cer: 'Please upload professional tax Registrtion Certificate',
    Id_Number: 'ID Number',
    Bank_Name: 'Bank Name',
    Inavid_Date: 'Please Enter Valid Birth Date.',
    Notarized: 'Notarized',
    Registered: 'Registered',
    Rent_Agreement_Type: 'Rent Agreement Type',
    Utility_Bill: 'Utility Bill',
    Document_Type: 'Document Type',
    Business_Address_Details: 'Business Address Details',
    ITR_Doc: 'Please upload ITR Document',
    Doc_upload1: 'Please upload ',
    Doc_upload2: ' Document',
    Date_Birth: 'Date of Birth',
    Doc_Exp_Date: 'Document Expiry Date',
    utilityBill: 'Utility Bill should not be more than 3 months old',
    mismatchDesc: 'Make sure that you have uploaded correct document.',
    mismatchName: 'Mismatch found in Entity Name!',
    expiryDate: 'Document Expiry Date should not be within 3 months',
    kycComplete:
      'Congratulations! You have successfully submitted all KYC documents',
    ePDF: 'E-pdf Bank Statement',
    scanAndUpload: 'Scan & Upload Physical Bank Statement',
    pdfProtected: 'Is e-pdf Bank Statement password protected?',
    uploadEpdf: 'Please Upload e-pdf Bank Statement',
    uploadDone: 'E-pdf Bank Statement Uploaded',
    uploadPennyDrop: 'Initial Funding Cheque Uploaded',
    uploadScanDoc: 'Please Upload Scanned Bank Statement',
    captureThumbprint: 'Capture Thumbprint',
    edtAdharNo: 'Edit Aadhar Number',
    bsAddressNotAvailable: 'bsAddressNotAvailable',
    bsbankNameMismatch: 'bsbankNameMismatch',
    bsInvalidBankStatement: 'bsInvalidBankStatement',
    bsAccountNotActivated: 'bsAccountNotActivated',
    bsPanMismatch: 'bsPanMismatch',
    bsEntityNameMismatch: 'bsEntityNameMismatch',
    bsPennyDropFail: 'bsPennyDropFail',
    pf_title: 'More Details Required!',
    upload_check: 'Upload cancelled/Intitial Funding cheque image.',
    cancelled_check: 'Please Upload Cancelled/Initial Funding Cheque',
    more_details: 'Required some more details to proceed ahead.',
  },
  AddBusinessDetails: {
    Section_1_Title: 'Basic Business Details',
    Section_2_Title: 'Business Address and Contact Details',
    Section_3_Title: 'Communication Address and Contact Details',
    Line_of_business: 'Line of. Business',
    Nature_of_Industry: 'Nature of Industry',
    Date_of_Incorporation: 'Date of Incorporation',
    Annual_Turnover: 'Annual Turnover',
    International_Trade_Turnover: 'International Trade Turnover',
    PEP: 'PEP',
    Yes: 'Yes',
    No: 'No',
    Please_upload: 'Please Upload ',
    Upload_For_IEC_Doc: ' for IEC',
    Country: 'India',
    Required_Fields: 'Please provide all required fields.',
    Required_LOB: 'Please select Line of Business.',
    Required_NOI: 'Please select Nature of Industry.',
    Required_Annual_Turnover: 'Please select Annual Turnover.',
    Business_Mobile_Not_Valid:
      'Business Mobile Number is not valid, please enter valid number and try again.',
  },
  AddProprietorDetails: {
    Section_1_Title: 'Proprietor Name',
    Section_2_Title: 'Personal Details of the Proprietor',
    Section_3_Title: 'Proprietor Address and Contact Details',
    Section_4_Title: 'Sole Proprietor Photograph and Signature',

    APD_FirstName: 'First Name',
    APD_MiddleName: 'Middle Name',
    APD_LastName: 'Last Name',
    APD_Gender_Female: 'Female',
    APD_Gender_Male: 'Male',
    APD_Gender_Other: 'Other',
    APD_Fathers_Name: "Father's Name",
    APD_Mothers_Name: 'Mother’s Maiden Name',
    APD_AddressLine1: 'Business Address Line 1',
    APD_AddressLine2: 'Business Address Line 2',
    APD_AddressLine3: 'Business Address Line 3',
    APD_Landmark: 'Landmark (Optional)',
    APD_City: 'City',
    APD_District: 'District',
    APD_Pincode: 'Pincode',
    APD_State: 'State',
    APD_Country: 'Country',
    APD_Mobile: 'Mobile',
    APD_Landline: 'Landline (Optional)',
    APD_Email: 'Email',
    APD_Capture_Photograph: 'Capture Photograph',
    upload_signature: 'Please Upload Customer Signature',
    APD_enter_fatherName:
      "*Uh-oh, seems like you have entered a special character in father's name",
    APD_enter_motherName:
      "*Uh-oh, seems like you have entered a special character in mother's name.",
    APD_enter_maidenName:
      '*Uh-oh, seems like you have entered a special character in mother’s Maiden Name.',
    APD_cob:
      '*Uh-oh, seems like you have entered a special character in country of birth.',
    APD_cot:
      '*Uh-oh, seems like you have entered a special character in country of TAX Residency.',
    APD_nationality:
      '*Uh-oh, seems like you have entered a special character in nationality.',
    APD_address1:
      '*Uh-oh, seems like you have entered a special character in proprietor address line 1.',
    APD_address2:
      '*Uh-oh, seems like you have entered a special character in proprietor address line 2.',
    APD_address3:
      '*Uh-oh, seems like you have entered a special character in proprietor address line 3.',
    APD_error_landmark:
      '*Uh-oh, seems like you have entered a special character in landmark.',
    APD_error_city:
      '*Uh-oh, seems like you have entered a special character in city.',
    APD_error_district:
      '*Uh-oh, seems like you have entered a special character in district.',
    APD_error_Pincode:
      '*Uh-oh, seems like you have entered a special character in pincode.',
    APD_error_State:
      '*Uh-oh, seems like you have entered a special character in state.',
    APD_error_Country:
      '*Uh-oh, seems like you have entered a special character in country.',
    APD_error_Mobile:
      '*Uh-oh! Seems like you have entered an invalid mobile number or special character.',
    APD_error_Landline:
      '*Uh-oh, seems like you have entered an invalid landline.',
    APD_error_Email: '*Uh-oh, seems like you have entered an invalid email.',
  },

  // Step No : 2 Product Selection -----------------------------------------
  ProductSelection: {
    Section_1_Title: 'Select a Variant to View Features and Benefits',
    Section_2_Title: 'Current Account Feature Details',
    Section_3_Title: 'Debit Card Details',
    Section_4_Title: 'Doorstep Banking Details',
    Variant_Header_Title: 'Product Variant Selection',
    Variant_Header_Detail:
      'Help your proprietor choose the Current Account best suited for their business',
    Select_Current_Account_Variant: 'Select Current Account Variant',
    Regular_Business_Account_10K: 'Regular Business Account - 10K',
    Dynamic_Business_Account: 'Dynamic Business Account',
    Current_Account_10K: 'Current Account - 10K',
    Current_Account_25K: 'Current Account - 25K',
    Current_Account_50K: 'Current Account - 50K',
    Current_Account_1L: 'Current Account - 1L',
    World_Business_Account_50K: 'World Business Account - 50K',
    World_Business_Account_1L: 'World Business Account - 1L',
    World_Business_Account_25K: 'World Business Account - 25K',
    Customizable_Current_Account_50K: 'Customizable Current Account - 50K',
    Freedom_CA: 'Freedom Current Account',
    Freedom_World_Business_Account: 'Freedom World Business Account',
    Merchant_Multiplier_Account: 'Merchant Multiplier Account',
    New_Business_Account: 'New Business Account',
    DSA_Dynamic_Business_Account: 'DSA Dynamic Business Account',
    Internet_Banking: 'Internet Banking',
    Yes: 'Yes',
    No: 'No',
    Offer_Related_SMS: 'Offer Related SMS',
    Statement_Via_Email: 'Statement Via Email',
    Frequency: 'Frequency',
    Daily: 'Daily',
    Weekly: 'Weekly',
    Forthnightly: 'Forthnightly',
    Monthly: 'Monthly',
    Cheque_Book: 'Cheque Book',
    Leaves_25: '25 leaves',
    Leaves_50: '50 leaves',
    Not_Required: 'Not required',
    Avail_Debit_Card: ' Avail Debit/ATM card?',
    Doorstep_Banking: 'Doorstep Banking',
    Communication_Address: 'Communication Address',
    Ad_hoc: 'Ad-hoc',
    Beat: 'Beat',
    Best_inclass_platform: 'Best in-class net banking platform!',
    Adv_details:
      'Enjoy GPS-enabled doorstep banking and higher cash deposit limits with IDFC FIRST Bank Current Account',
    New_Offer: 'NEW OFFER',
  },

  // Step No : 3 Declaration Review -----------------------------------------
  DigitalDeclaration: {
    Section_1_Title: 'Proprietor Declaration',
    Section_2_Title: 'Nominee Details',
    Section_3_Title: 'Credit Facility Declaration',
    Section_4_Title: 'GST Annexure',
    Section_5_Title: 'Aadhaar Declaration',
    Section_6_Title: 'Vernacular Declaration',
    Section_7_Title: 'Signature Mismatch Declaration',
    addDeclaration: 'Add Declaration',
    addDeclarations: 'Add Declarations',
    vernacularDeclaration: 'Vernacular Declaration',
    signatureMismatchDeclaration: 'Signature Mismatch Declaration',
    deleteDeclaration: 'Delete Declaration',
  },
  VernacularDeclaration: {
    declarationDesc:
      'hereby state and declare that I have signed all the documents and agreements in the vernacular after the bank officer explained to me in detail. ',
  },
  SignatureMismatchDeclaration: {
    declarationDesc:
      'state and declare that the signature on the ID proof/Address proof/Cheque provided is different from my signature on account opening form. Please consider the signature on the account opening form as my updated signature in your bank records. ',
  },
  NomineeDetails: {
    Nominee_Option_YES_Desc:
      'Yes, I want to nominate the following person to whom in the event of my/our/minor’s death the amount of deposit in the account may be returned by IDFC First Bank Ltd.',
    Nominee_Option_NO_Desc:
      'No, I do not wish to nominate anyone on my behalf at this moment. I understand the advantantages of nomination and the consequenses of not nominating anyone to my account.',
    Mention_Nominee_On_Account_Statement_Desc:
      'Mention nominee name on my account statements/advices',
    Set_Nominee_Address: 'Nominee Address is same as Proprietor’s Address',
    Guardian_Address_Radio_Label:
      'Guardian Address is same as Nominee’s Address',
    Nominee_First_Name: "Nominee's First Name",
    Nominee_Middle_Name: "Nominee's Middle Name (Optional)",
    Nominee_Last_Name: "Nominee's Last Name",
    Nominee_RelationShip_Label: 'Relationship with Proprietor',
    Date_Birth: "Nominee's Date of Birth",
    Nominee_AL1: 'Nominee Address Line 1',
    Nominee_AL2: 'Nominee Address Line 2',
    Nominee_AL3: 'Nominee Address Line 3',
    Nominee_Landmark: 'Landmark (Optional)',
    Guardian_First_Name: "Guardian's First Name",
    Guardian_Middle_Name: "Guardian's Middle Name (Optional)",
    Guardian_Last_Name: "Guardian's Last Name",
    Guardian_AL1: "Guardian's Address Line 1",
    Guardian_AL2: "Guardian's Address Line 2",
    Guardian_AL3: "Guardian's Address Line 3",
  },
  GSTAnnexure: {
    GST_Status: 'GST Status',
    exemptedFromGST: 'Are you exempted from GST?',
    relatedIDFCPerson: 'Related person to IDFC FIRST Bank',
    Registered: 'Registered',
    Unregistered: 'Unregistered',
    customerLevelExemption: 'Customer Level Exemption',
    accountLevelExemption: 'Account Level Exemption',
    Name_Of_State: 'Name of State',
    GST_Registration_Number: 'GST Registration Number',
    Address_As_GSTN_Records: 'Address as per GSTN records',
    AddressLine1: 'Address Line 1',
    AddressLine2: 'Address Line 2',
    AddressLine3: 'Address Line 3',
    Remarks: 'Remarks',
    Address_Type_Other: 'Other',
    Address_Type_Business_Address: 'Business Address',
    Address_Type_Communication: 'Communication Address',
    Remark: 'Remark',
    State_Wise_GST_Details: 'State wise GST details',
    pleaseUploadGSTCertificate: 'Please upload GST Certificate Document',
  },
  CreditFacilityDeclaration: {
    title:
      'I /We wish to open Current account with IDFC FIRST Bank and declare that:',

    //negative feedback
    Do_Not_Enjoy: 'l/We do not enjoy any',
    CreditFcility: ' Credit Facility',
    commericalBank: ' from any commercial and Payment Banks.',
    Including: ' including',
    CC_OD: ' Cash Credit (CC)/Overdraft (OD)',
    Facility_From: ' facility from',
    IDFC_First_Bank: ' IDFC FIRST Bank',
    Or_Any: ' or any',
    Other_Bank: '  other Bank.',
    Inform: ' I/We shall inform',
    Any_Other_Bank: '  or any other Bank',
    Available: ' if and when l/we avail any',
    CC_OD_Facility: ' CC/OD facility',
    Scenario:
      ' from any other bank and under such scenario. it would be the discretion of',
    Close_Current_Account: ' to close the said current account.',
    I_We: 'I/We',
    I_We_Have: 'I/We have',
    Availed_CCOD: ' have availed CC/OD',
    IDFC_First_Bank_Enjoy_Credit_Facility:
      ' IDFC FIRST Bank and enjoy credit facilities',
    of: ' of',
    More_Thank_5_Crore: '  more than ₹5 crores',
    Do_Not_Have_Account_Other_Bank:
      '  from the Scheduled commercial and Payment Banks. Also, I/We confirm that we do not have current account with any other Scheduled Commercial and Payment Banks.',
    Enjoy_Facility_5to50_crores:
      ' not availed CC/OD facility and enjoy credit facilities of ₹5 crores to ₹50 crores',
    Credit_Relation_IDFC_BANK:
      ' from the Scheduled commercial and Payment Banks having credit relationship with IDFC FIRST Bank.',
    Not_Availed_Enjoyed_Credit_5to50_Crores:
      ' not availed CC/OD facility and enjoy credit facilities of ₹5 crores to ₹50 crores',
    Not_Availed_CCOD_Enjoy_Credit:
      ' not availed CC/OD facility and enjoy credit facilities',
    More_Thank_50_Crores:
      ' of more than ₹50 crores from the Scheduled commercial and Payment Banks and have an Escrow arrangement with IDFC FIRST Bank.',

    //positive feedback
    Enjoy: 'l/We enjoy',
    From: ' from',
    IDFC_Other_Bank: ' IDFC FIRST Bank/Other Bank',
    As_Below: ' as below:',

    //generalDesc
    I_We_HearBy_Declare: 'I/We here declare that',
    I_We_Inform_IDFC_Bank: ' I/we shall inform IDFC FIRST Bank',
    Avail_CCOD_Facility_Upon_Cross_Amount:
      ' on availing CC/OD facility and /or upon crossing the amount of credit facilities availed by us from the banking system',
    Abov_5and50_Crore: ' above ₹5 crore and/or ₹50 crores or above',
    generalDescParagraph2:
      '\n \n Under such scenario, it would be the discretion of IDFC FIRST Bank to continue/close the current account or convert the same to a collection account subject to the condition that funds lying in the said current account will be remitted to the escrow account / CC/ OD / Current account maintained with my/our lending bank at the frequency agreed between the us and IDFC FIRST Bank as per RBI guideline issued from time to time.',

    //First positive feedback string splitting
    creditFacilityLessThan: 'I/We enjoy credit facilities of less than',
    fiveCrore: ' ₹5 crores',
    fromTheScheduleCommerialPaymentBank:
      ' from the Scheduled commercial and Payment Banks.',

    lessThan5CroreFacilityDesc:
      'I/We enjoy credit facilities of less than ₹5 crores from the Scheduled commercial and Payment Banks.',
    moreThan5CroreFromScheduledBank:
      'I/We have availed CC/OD facility from IDFC FIRST Bank and enjoy credit facilities of more than ₹5 crores from the Scheduled commercial and Payment Banks. Also, I/We confirm that we do not have current account with any other Scheduled Commercial and Payment Banks.',
    fiveTo50CroreFcilityDecs:
      'I/We have not availed CC/OD facility and enjoy credit facilities of ₹5 crores to ₹50 crores from the Scheduled commercial and Payment Banks having credit relationship with IDFC FIRST Bank.',
    moreThan50Crore:
      'I/We have not availed CC/OD facility and enjoy credit facilities of more than ₹50 crores from the Scheduled commercial and Payment Banks and have an Escrow arrangement with IDFC FIRST Bank.',
    negativeFeedbackText:
      'I/We do not enjoy any credit facility from any commercial and Payment Banks.',
    Credit_Facility_Available:
      ' if and when the credit facilities availed by me/us from the banking system crosses the limit of becomes',
    Credit_Price: ' ₹5 crore and/or ₹50 crore',
    Price_Applicable_Scenario:
      ' (Whenever applicable). Under such scenario it would be in the discretion of',
    Convert_Account:
      ' to close my/our current account or convert the same to a collection account subject to the condition that funds lying in the said current account will be remitted to the',
    Escrow_Account: ' escrow account/CC/OD/Current account',
    Maintained_Lending_Bank:
      ' maintained with my/our lending bank at the frequency agreed between me/us and',
    Request_Open_Account:
      '\n \n I/We hereby request to consider my/our request to open a current account basis this declaration.',

    // negativeFeedbackText:
    //   'I/We do not enjoy any Credit Facility including Cash Credit (CC)/Overdraft (OD) facility from IDFC FIRST Bank or any other Bank. I/we shall inform IDFC FIRST Bank, if and when l/we avail any CC/OD facility from any other bank and under such scenario. it would be the discretion of IDFC FIRST Bank to close the said current account.',
    positiveFeedbackText:
      'I/We enjoy credit facilities of less than ₹5 crores from the Scheduled commercial and Payment Banks.',
    generalDesc:
      'I/We shall inform IDFC FIRST Bank if and when the credit facilities availed by me/us from the banking system crosses the limit of becomes ₹5 crore and/or ₹50 crore (Whenever applicable). Under such scenario it would be in the discretion of IDFC FIRST Bank to close my/our current account or convert the same to a collection account subject to the condition that funds lying in the said current account will be remitted to the escrow account/CC/OD/Current account maintained with my/our lending bank at the frequency agreed between me/us and IDFC FIRST Bank.l/We hereby request to consider my/our request to open a current account basis this declaration. \n \n l/We hereby request to consider my/our request to open a current account basis this declaration.',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    facilityType: 'Facility Type',
    accountNumber: 'Account Number',
    sanctionedAmount: 'Sanctioned Amount',
    addAditionalBank: 'Add Additional Bank',
    removeBank: 'Remove Bank',
  },
  AadhaarDeclaration: {
    Aadhaar_Declaration:
      'declare, confirm and agree that the Bank has duly explained to me that submission of a copy of my Proof of Possession of Aadhaar Number (OVD) containing Aadhaar number, as an Officially Valid Document (OVD) is not mandatory and I have the option to submit any one of the documents as per the list of Officially Valid Documents (updated by the RBI from time to time). I further state, declare and confirm that I am are providing my Proof of Possession of Aadhaar number (OVD) as an officially valid document voluntarily in accordance with extant rules and regulations. I authorize IDFC FIRST Bank to redact/blacken out the Aadhaar number through appropriate means on my behalf. I enclose herewith the Self attested copy of my Aadhaar Card as Identity and/or Address Proof.',
  },
  ReviewDetails: {
    Section_1_Title: 'Business Details',
    Section_2_Title: 'Proprietor Details',
    Section_3_Title: 'Product Selection',
    Section_4_Title: 'Declaration and Nominee Details ',
    Location: 'Location',
    Pro_Declaration_Text1:
      ' hereby declare that I am the sole proprietor of the firm under the name of ',
    Pro_Declaration_Text2:
      ' and I am solely responsible for the liabilities thereof. I shall advise you in writing of any changes that takes place in the constitution of the firm and I will be liable to you for any obligation which may be standing in the firm name in your books on the date of receipt of such notice and until all such obligations shall have been liquidated.',
    Current_Account_Varient: 'Current Account Varient',
    Statement_Frequency: 'Statement Frequency',
    Contact_Person: 'Contact Person',
    Mobile_Number: 'Mobile Number',
    Name_On_Card: 'Name on the card',
    Branch_Name: 'Branch Name',
    SubTitle_1: '1. Proprietor Declaration',
    SubTitle_2: '2. Nominee Details',
    SubTitle_3: '3. Credit Facility Declaration',
    SubTitle_4: '4. GST Annexture',
    SubTitle_5: '5. Aadhar Declaration',
    SubTitle_6: '6. Vernacular Declaration',
    SubTitle_7: '7. Signature Mismatch Declaration',
    ThankYouTitle: 'Thank You ',
    ThankYouDetail:
      'Please hand over the device back to the Bank Executive to complete other steps for you!',
    ReviewOTPTitle: 'Please verify via Authentication Code',
    ReviewOTPDetail:
      'Please confirm that you have checked and reviewed the declarations. Please enter verification code received on the mobile number provided.',
  },
  CustomerInformationForm: {
    Section_1_Title: 'Customer Information Form',
    MITC_Form: 'Please upload MITC form',
    Signature: 'Please upload Customer Signature',
    Barcode: 'Barcode Number',
  },
  BuiltInCamera: {
    Capture_Camera: 'Capture Via Camera',
    Upload_Onedrive: 'Select From One Drive',
    title: 'Upload Document',
    message: '',
    actionName: 'Cancel',
  },
  AddInitialFunds: {
    Section_1_Title: 'Add Funds to Your Customer’s Selected CA Variant',
    Section_2_Title: 'Add Funds',

    Cheque_Detail: 'Cheque Details',
    Cheque_Image: 'Please upload Cheque Image',
  },

  TermsAndConditions: {
    Declaration_TEXT1: ' I have read the declarations and agree to the',
    Declaration_TEXT2: ' Terms and Conditions',
    Declaration_TEXT_Title: 'Terms and Conditions Document ',
    Declaration_TEXT_Message:
      '1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget porttitor diam. Vivamus porta aliquam mauris. Nullam pharetra molestie lacus id volutpat. Etiam commodo tellus erat, ac posuere augue convallis ut. In hac habitasse platea dictumst. Cras cursus orci non quam consequat sollicitudin. Proin finibus, sem sed ultrices ultrices, mi risus rutrum nibh, in vehicula enim sem non ligula. Maecenas euismod velit sit amet turpis varius laoreet. 2. Aenean vitae ipsum tellus. Fusce rhoncus, enim at euismod tincidunt, augue ante dignissim justo, sit amet fermentum enim nisl et ipsum. Proin porttitor aliquet neque, at luctus tellus mollis ac. 3. Mauris suscipit erat orci, eget fringilla lorem scelerisque at. Aenean congue tellus sed urna hendrerit finibus. Praesent rutrum bibendum metus sit amet accumsan. Donec ac dapibus turpis. Duis fringilla bibendum aliquet. Donec et venenatis erat, ut placerat magna. 4. Morbi finibus massa eros, eu luctus enim mollis et. Ut auctor tortor in viverra ornare. Duis pharetra justo ex, at ornare risus tempus non. Aenean elementum maximus diam eu rutrum. Duis vel nunc at sem feugiat lobortis. 5. Nam et arcu quis dui placerat rutrum. Donec volutpat mattis mollis. Fusce pulvinar, tortor vel bibendum vestibulum, nisi ligula cursus dui, at rutrum urna sapien ac nunc. Sed eleifend, arcu at consectetur accumsan, neque turpis varius nisl, sit amet pulvinar libero nisi nec libero. Vivamus semper neque vitae suscipit ullamcorper. Nam vitae vehicula ligula, molestie varius ipsum. Nam in neque porta, dignissim purus quis, suscipit purus. Donec placerat suscipit metus, at malesuada tellus fermentum vitae. 6. Sed libero magna, porttitor ac metus non, luctus maximus leo. Praesent non commodo magna, vitae semper purus. Vivamus interdum enim eget tincidunt porta. Aliquam porttitor metus diam, a convallis enim efficitur eu. Integer sed semper nunc. Quisque tincidunt lectus magna, vitae semper lectus porttitor quis. Sed non tortor luctus, semper ligula in, tristique lacus. 7. Mauris suscipit erat orci, eget fringilla lorem scelerisque at. Aenean congue tellus sed urna hendrerit finibus. Praesent rutrum bibendum metus sit amet accumsan. Donec ac dapibus turpis. Duis fringilla bibendum aliquet. Donec et venenatis erat, ut placerat magna. Morbi finibus massa eros, eu luctus enim mollis et. Ut auctor tortor in viverra ornare. Duis pharetra justo ex, at ornare risus tempus non. Aenean elementum maximus diam eu rutrum. 8. Duis vel nunc at sem feugiat lobortis. Nam et arcu quis dui placerat rutrum. Donec volutpat mattis mollis. Fusce pulvinar, tortor vel bibendum vestibulum, nisi ligula cursus dui, at rutrum urna sapien ac nunc. Sed eleifend, arcu at consectetur accumsan, neque turpis varius nisl, sit amet pulvinar libero nisi nec libero. Vivamus semper neque vitae suscipit ullamcorper. 9. Nam vitae vehicula ligula, molestie varius ipsum. 10. Nam in neque porta, dignissim purus quis, suscipit purus. Donec placerat suscipit metus, at malesuada tellus fermentum vitae. Sed libero magna, porttitor ac metus non, luctus maximus leo. Praesent non commodo magna, vitae semper purus. Vivamus interdum enim eget tincidunt porta. Aliquam porttitor metus diam, a convallis enim efficitur eu. Integer sed semper nunc. 11. Quisque tincidunt lectus magna, vitae semper lectus porttitor quis. Sed non tortor luctus, semper ligula in, tristique lacus.',
  },

  // Step 6 : Bank Use
  BankUse: {
    Bank_Certification: 'Bank Certification',
    Site_Verification_Desc: 'I have completed site verification at customer’s',
    KYC_Verification_Desc:
      'I have seen the original KYC documents and returned these to customer.',
    Signature_Vertification_Desc: 'The customer has signed in my presence.',
    Business_Address: 'Business Address',
    Communication_Address: 'Communication Address',
    leadDetails: 'Lead Details',
    validLeadConverter:
      '*Please note! Lead converter field should be of 6 digits and should not contain any special characters.',
    validLeadGenerator:
      '*Please note! Lead generator field should be of 6 digits and should not contain any special characters.',
    validLeadWarmer:
      '*Please note! Lead warmer field should be of 6 digits and should not contain any special characters.',
    validPromocode:
      '*Please note! Promo Code should not be less than 15 digits and should not contain any special characters.',
    validCampaignCode:
      '*Please note! Campaign Code should not be less than 15 digits and should not contain any special characters.',
    approval: 'Approval',
    addApproval: 'Add Approval',
    systemFlagApproval: 'System Flagged Approvals',
    manuallyApproval: ' Manually Initiated Approvals',
    exception: 'Exception',
    desi: 'Approvar Designation',
    uploadApprovalDoc: 'Please Upload the Approval',
    ns_internalCheck:
      'Aw-snap! Technology can be difficult sometimes. This will take some time, please wait.',
    ns_completeInternalCheck: 'Complete Internal Checks',
    Screening_Reports: 'Screening Reports',
  },

  SiteVerificationReport: {
    Entity_Commn_Addr: 'Entity Communication Address',
    Business_Premise_Photographs: 'Business Premise Photographs',
    Other_Details: 'Other Details',
    Communication_Address: 'Communication Address',
    Sample_Address:
      '117-AB, Near Hindistan Naka , Co-operative Industrial Estate, Kandivali, MCA Building, Mumbai - 400067, Maharshtra',
    Address_Not_Matched:
      'Mismatch in communication address. You are not within 100m from the communication address. Make sure you are at correct location or recheck the entity communication address.',
    Verified_BY: 'Validated by',
    Geotag: 'Geotag',
    //Entity Information
    CustomerName: 'Customer Name',
    DateOfIncorporation: 'Date of Incorporation',
    NewlyIncorporated: 'Newly Incorporated',
    NoYearsActiveBusiness: 'No. of Years for active business',
    LineOfBusiness: 'Line of Business',
    AnyRelatnIDFCFB: 'Any Banking Relationship with IDFC First Bank',
    CommunicationAddress: 'Communication Address',
    BusinessAddress: 'Business Address',
    SourceOfLead: 'Source of Lead',
    MentionOtherSourceOpt: 'Mention Other Source of Lead (Optional)',
    PvtLtdPROBE: 'Pvt.Ltd & Validated PROBE & SARVA',
    NatureOfBusiness: 'Nature of Business',
    NameOfCompanyInAbbreviation: 'Name of the Company in Abbreviation',
    MatchingAbbreviation: 'Matching Abbreviation on Google Search',
    EaseOfLocatingSite: 'Ease of Locating Site',
    PhysicalAppearanceBuilding: 'Physical Appearance of the Building',
    NatureOfOwnershipAddress: 'Nature of Ownership Address',
    EntityDirectorOpt: 'Entity is Director/Trustee/Promoter (Optional)',
    OperatedMultipleLocations: 'Operated from Multiple Locations',
    egIATAIMAFICCI: 'e.g. IATA, IMA, and FICCI',
    //Address verification Details
    DetailsOfBusinessAddress: 'Details of Business Address',
    CommAddrSameBussAddr: 'Communication address same as Business Address',
    Easy: 'Easy',
    Difficult: 'Difficult',
    Untraceable: 'Untraceable',
    Excellent: 'Excellent',
    Good: 'Good',
    Poor: 'Poor',
    NatureOfOwnershipOfAddress: 'Nature of Ownership of Address',
    Owend: 'Owend',
    Rented: 'Rented',
    PG: 'PG',
    YearsOperatingAddress: 'Years of Operating From This Address',
    MentionTotalYears: 'Mention total years e.g. 1 year 1 month',
    DoesCustomerFromMultipleLocations:
      'Does the Customer operated from multiple locations?',
    NumberOfSuchAddresses: 'Number of Such Addresses',
    ReasonMultipleOpt: 'Reason of Multiple Locations (Optional)',
    ReasonMultipleReq: 'Reason of Multiple Locations',
    IsMoreThanCompanyFromSameAddr:
      'Is more than one Company/Entity operation from same address?',
    ReasonOptional: 'Reason (Optional)',
    ReasonRequired: 'Reason',
    AddressLocality: 'Address Locality',
    SingnageType: 'Type Of Signage ',
    PleasesharReason: 'Please share the reason ',
    MentionAddressLocalityReq: 'Mention Other Address Locality',
    MentionAddressLocalityOptional: 'Mention Other Address Locality (Optional)',
    TypeOfOffice: 'Type of Office',
    DetailsOfCommunicationAddress: 'Details of Communication Address',
    AddressProofCollected: 'Address Proof Collected',
    ReasonDifferentCommAddressOpt:
      'Reason of Different Communication Address (Optional)',
    ResidencyForDirector:
      'In case this is residency for Director/ Trustee/ Promoter, does the profile of the entity match with the profile of Director/ Trustee/ Promoter?',
    //Business Activity
    WasBusinessBoardOutside:
      'Was the Business Board, Signage seen outside the Business Address?',
    TypeOfSignageOptional: 'Type of Signage (Optional)',
    DoesBoardMatchAccountTitle: 'Does the board match the account Title?',
    PleaseShareReason: 'Please share the reason',
    IEShortFamous: ' i.e. short, famous',
    WereNeighboursAwareCustomer:
      'Were the neighbours (shops/office) aware of the customer/entity?',
    DetailsFeedbackNeighbour: 'Details of feedback from the neighbour',
    IEBusinessActivity:
      'i.e. business activity, period since the office/shop has been active, their iteration or any other observation',
    LevelActivitySeen: 'Level of activity seen',
    High: 'High',
    Low: 'Low',
    PoorNoActivity: 'Poor (no activity)',
    NoOfEmployeesWorking: 'No. of employees seen working',
    WasActivityAlignedWithNatureAndLineOfBusiness:
      'Was the activity aligned with the nature & line of business?',
    WasNecessaryInfrastructureOfBA:
      'Was the necessary infrastructure sighted in line with business activity?',
    IEComputerTerminals: 'i.e. computer terminals, machinery',
    //Details of Key decision makers & authorised signatories
    WhoWasMetTimeOfConductingSVR: 'Who was met at the time of conducting SVR',
    Designation: 'Designation',
    Name: 'Name',
    PleaseCaptureMentionedDetailsAUTHORISEDSIGNATORIES:
      'Please capture below mentioned details of ALL AUTHORISED SIGNATORIES',
    Age: 'Age',
    HoldingThePositionSince: 'Holding the position since (years)',
    NoOfYearsExperience: 'No of yrs. of Experience in similar field',
    AddAuthorisedSignatory: 'Add Authorised Signatory',
    //Maker/Checker recommendation
    IHereByRecommendDm:
      'I hereby recommend account opening as I have conducted due diligence at the place of business, verified the KYC documents and checked the profile of the signatories & key decision makers,',
    MakerName: 'Maker Name',
    EmployeeCode: 'Employee Code',
    SelectDate: 'Select Date',
    PleaseUploadCustomerSignature: 'Please Upload Customer Signature',
    IHereByRecommend:
      'I hereby recommend account opening, am aware that the below mentioned parameters is/are true and have been addressed satisfactorily.',
    OfficeIsRentedPG: 'Office is rented P.G',
    NameOfAbbreviation: 'Name of co.is in abbreviation',
    BoardNotSeen: 'Board not seen',
    BusinessActivitySeenIsPoor: 'Business activity seen is poor',
    CommentsReq: 'Comments',
    CommentsOpt: 'Comments (Optional)',
    CheckerName: 'Checker Name',
    LevelOfActivity: 'Level of activity seen',
    EmployeeSeenWorking: 'No. of employees seen working',
    AbbreviationRequired: 'Reason of Abbreviation Used',
    AbbreviationOptional: 'Reason of Abbreviation Used (Optional)',
    DetailedFeedbackNeighbour: 'Details of feedback from the neighbour',
  },

  ChoiceAccountNumber: {
    ChooseAccountNumber: 'Choose an Account Number',
    SelectAMode: 'Select a mode to get your account number created',
    CustomizeAccNo: 'Customize account number',
    SkipCustomization: '   Skip',
    ChooseSystemGeneratedNo: 'Choose a system generated number',
    CustomizeYourAccNo:
      'You can customize your account number using following options',
    UseMobileNumber: 'Use mobile number',
    UseDOB: 'Use Date of Birth',
    WouldLikeToChoose: 'I would like to choose',
    MyOwnNo: 'my own numbers',
    InputYourPreferredNumber: 'Please put your preferred number',
    FirstNumberCanOnlyBe: 'First number can only be 5,6,7 or 8',
    Dot: '●   ',
    SuggestionOne:
      'You can enter a minimum of 3 number and a maximum of 10 numbers',
    YouCanEnter: 'You can enter a',
    MinimumOf3: 'minimum of 3',
    NumberAndA: 'number and a',
    MaximumOf10: 'maximum of 10 consecutive',
    Numbers: 'numbers.',
    SuggestionTwo:
      'Numbers not entered by you will be automatically system generated.',
    Choose: 'Choose',
    AvailableOptions: 'from one of the available options below',
    StartWith: 'Start with',
    EndWith: 'End with',
    Anywhere: 'Anywhere',
    AccountNoNotAvailable: 'Account Number Not Available!',
    AccountNoNotAvailableDetails:
      'Account number not available with mentioned choice of numbers. Please select other options for generating account number to proceed.',
    SelectOtherOption: 'Select Other Option',
    SkipTheStep: 'Skip the Step',
    Back: 'Back',
    SystemError: 'System Error',
    PleaseTryAfter: 'Please try after some time or',
    SystemGeneratedNo: 'to get system generated number.',
    Congratulations: 'Congratulations!',
    YouHave: 'You have',
    SuccessfullyCreated: 'successfully created',
    AccNoForCustomer: 'the account number for your customer.',
    PleaseFind: 'Please find the',
    AccNo: 'Account Number',
    Below: 'below:',
    PleaseNote: 'Please note the account number selected is',
    ValidFor45Days: 'valid for 45 days',
    PleaseCreateAnAcc: 'only. Please create an account within 45 days.',
    AccNoCreated: 'Account Number Created!',
    PleaseNoteOnceConfirmed: 'Please note that the account number',
    CanNotChange: 'cannot be changed',
    OnceConfirmed: 'once confirmed.',
    ConfirmedAndProceed: 'Confirm and Proceed',
    EditAccNo: 'Edit Account Number',
  },

  // ----------------------------------------------------------------------------------------------
  // This needs to delete later on as list of document get from the server through API
  // These are just dummy data
  DocumentTypes: {
    Aadhar_Card: 'Aadhar Card',
    Driving_License: 'Driving License',
    Voter_ID: 'Voter ID',
    Passport: 'Passport',
    NPR_Letter: 'NPR Letter',
    Marriage_Certificate: 'Marriage Certificate',
  },

  Salutaions: [
    'Mr.',
    'Ms.',
    'Miss',
    'Dr.',
    'Master',
    'M/s.',
    'Lieutenant',
    'Captain',
    'Major',
    'Colonel',
  ],

  StateList: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Ladakh',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttarakhand',
    'Uttar Pradesh',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Lakshadweep',
    'Puducherry',
  ],

  BusinessLinesList: [
    'Manufacturing',
    'Service Provider',
    'Retail Trade',
    'Wholesale Trading',
    'E-Commerce',
    'Financial Services',
  ],

  IndustryNatureList: [
    'Advertising/Media / Entertainment',
    'Agriculture',
    'Airlines',
    'Architecture and engineering activities',
    'Arms/Antique/Art Dealer',
    'Auto Finance Co',
    'Automobile',
    'Bar/Casino/Night club',
    'Bullion/Forex Dealer',
    'Cement',
    'Chemicals/Dyes/Paints',
    'Civil engineering',
    'Construction/Real estate/ Builder',
    'Consultancy',
    'Consumer Durables',
    'Courier/ Freight Forwarders',
    'Dairy/Food Processing',
    'Dot-com Company or internet business',
    'Electric power generation , transmission and distribution',
    'Electronics/Computer Hardware',
    'Employment activities',
    'Engineering goods',
    'Event Catering',
    'Exchange house',
    'Fertilizers/Seeds/Pesticides',
    'Financial Advisory - Portfolio management services',
    'Financial Intermediation- NBFC',
    'Fishery/Poultry',
    'Furniture/Timber',
    'Gas - distribution of gaseous fuels',
    'Gems and Jewellery',
    'Government Contractors/Contractor',
    'Health Club/Spa',
    'Hotel/Resort',
    'Housing Finance Co',
    'Insurance Co',
    'Internet Café',
    'Investment Management/Money Management Company/Personal Investment Company',
    'Iron and Steel',
    'IT/Software/BPO/ITES',
    'Law firm',
    'Liquor Distributor',
    'Machinery and equipment',
    'Marble/Granite',
    'Merchant banking',
    'Mining',
    'Money services business ( remittance house, money transfer agents, bank note traders)',
    'Movie theatre',
    'Nursing home/clinic /Life science/Diagnostic Centre /Hospital',
    'Other pvt financial corp',
    'Pawn Shops',
    'Petroleum Oil and Gas',
    'Pharmaceuticals / Chemists',
    'Plastic/Paper and Allied products',
    'Printing/Publishing',
    'Realty and Infrastructure',
    'Rental and leasing activities',
    'Scrap Metal',
    'Security and investigation activities',
    'SEP (Doc, CA, Architect/Lawyer/Consultant)',
    'SEP (Entertainment/Alternate Medicine Practitioner/Beautician)',
    'sports goods , games and toys',
    'Store - Retail outlet (Bakery/Books/stationery/Garments)/Departmental/Grocery',
    'Telecom',
    'Term Lending Co',
    'Textiles/Garments/ Handloom',
    'Tour Travel and Tourism',
    'Transportation /Logistics',
    'Used car dealer',
    'Venture Capital Companies',
    'Veterinary activities',
    'Warehousing and support activities for transportation',
    'Waste collection, treatment and disposal activities; materials recovery',
  ],

  TurnOverRanges: [
    'Upto INR 100000',
    'INR 100001 to 5 LAKH',
    'INR 5 LAKH TO 10 LAKH',
    'INR 10 LAKH TO 25 LAKH',
    'INR 25 LAKH TO 50 LAKH',
    'INR 50 LAKH TO 3 CRORES',
    'INR 3 CRORES TO 5 CRORES',
    'INR 5 CRORES TO 10 CRORES',
    'INR 10 CRORES TO 15 CRORES',
    'INR 15 CRORES TO 20 CRORES',
    'INR 20 CRORES TO 35 CRORES',
    'INR 35 CRORES TO 50 CRORES',
    'INR ABOVE 50 CRORES',
    'NOT APPLICABLE',
  ],

  ApprovalDesignation: [
    'Cluster Head',
    'Regional Head',
    'Branch Manager',
    'Compliance',
  ],

  approvals: [
    'No documents (KYC Docs only; AOF is at record) 50K variant and above',
    'No documents (KYC Docs only; AOF is at record) variants below 50K',
    'Partial documents / Expired/ Close to Expiry documents for a/c opening (incl KYC docs)- (Account in Debit Freeze Status) 50K variant and above',
    'Partial documents / Expired/ Close to Expiry documents for a/c opening (incl KYC docs)- (Account in Debit Freeze Status) variants below 50K',
    'Partial Docs (excluding KYC docs) 50K variant and above',
    'Partial Docs (excluding KYC docs) variants below 50K',
    'Professional’s certificate not verified online',
    'Old AOF format (Upto 1 month)',
    'Old AOF format (Beyond 1 month)',
    'Choice account number',
    'Third Party IP (Vintage > 6 months)',
    'Third Party IP (Vintage < 6 months)',
    'IP funding through Outstation cheque',
    'Name mismatch - Entity',
    'Name variation on Rubber Stamp',
    'Document image not clear',
    'Signature Related(Signature Difference)',
    'Signature Related(Signature in Vernacular language/ Block letters/ Captial Letters)',
    'Difference in photo on KYC and AOF',
    'Product/Process/Compliance/Legal related',
    'Business',
    'Bureau Check',
  ],
  // ----------------------------------------------------------------------------------------------

  SourceOfLeadList: ['Wish List', 'CRM Lead', 'Activity', 'Branch', 'Other'],
  YesNoOption: ['Yes', 'No'],
  NatureOfBusinessList: ['Domestic', 'Export', 'Import', 'Export & Import'],
  EaseOfLocatingSiteList: ['Easy', 'Difficult', 'Untraceable'],
  PhysicalApprBuildingList: ['Excellent', 'Good', 'Poor'],
  AddressLocalityList: [
    'Commercial Complex',
    'Industrial Area/Estate',
    'Business Centre',
    'Residential',
    'SEZ',
    'Slum/Chawl',
    'Others',
  ],
  TypeOfOfficeList: [
    'Factory',
    'Small Production Unit',
    'Workshop',
    'Small Scale Shade',
    'Office Complex',
    'Indipendent Office Building',
    'Shared Office',
    'Shopping Complex',
    'Shop',
    'Residentical',
    'Others',
  ],
  SingnageTypeList: [
    'Backlit/Metal Fixture/Board',
    'Flex Banner',
    'Temporary Printed Banner',
  ],
  BoardAccountlist: [
    'Office of the Parent Entity',
    'Abbreviation used',
    'Others',
  ],
  NatureOwnershipAddressList: ['Owned', 'Rented', 'P.G.'],
};
