export default {
  OVERDRAFT_INFO: 'createODAgainstFD',
  CHECK_BOOK_SERIES: 'ChequeBookSeries',
  ACCESS_MANAGEMENT: 'manageAccess',
  ODEligibleAccountList: 'ODEligibleAccountList',
  OVERDRAFT: 'Overdraft',
  EEFC_TO_INR: 'EEFCToINR',
  CONVERT_EEFC_TO_INR: 'ConvertEefcToInr',
  MANAGE_OD_AGAINST_FD: 'ManageODAgainstFD',
  CLOSE_OD_AGAINST_FD_CONFIRMATION: 'CloseODAgainstFDConfirmation',
  MODIFY_OD_AGAINST_FD: 'ModifyODAgainstFD',
  VIEW_FD_LIST: 'ViewFDList',
  ACCOUNT_DETAILS: 'AccountDetails',
  CHANGE_INR_ACCOUNT: 'ChangeINRAccount',
  CHANGE_RATE: 'changeRateOption',
  OD_FACILITY: 'OdFacility',
  CONFIRM_EDIT_OD_DETAILS: 'confirmEditOdDetails',
  THREE_IN_ONE_ACCOUNT: '3in1account',
  ZEERODHA_ONE_CLICK: 'Zerodhaoneclick',
  INVEST_IN_IPO: 'investinipo',
  ORDER_BOOK: 'Order book',
  APPLY: 'Apply',
};
export const TRANSACTION_STATUSES = {
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN-PROGRESS',
  INITIATED: 'INITIATED',
};
