export default {
  preLogin: 'preLogin',
  postLogin: 'postLogin',
  DepositDetails: 'DepositDetails',
  deposits: 'deposits',
  DSB: 'doorStepBankingModal',
  ACCESS_MANAGEMENT: 'accessManagementModal',
  SERVICE_REQUEST: 'serviceRequestModal',
  CHEQUEBOOK_MANAGEMENT: 'chequeBookManagementModal',
  SETTINGS: 'settingsModal',
  SERVICE_REQUEST_FILTER: 'serviceRequestFilterModal',
  REMITTANCE: 'inwardRemittance',
  HOME: 'home',
  MORE: 'more',
  OVERDRAFT_INFO: 'createODAgainstFD',
  MY_FINANCES: 'My Finances',
  SCHEDULE_CALL_BACK_LIST: 'ScheduleCallBackScreen',
  SCHEDULE_CALL_BACK_LOGGED_IN: 'ScheduleCallBackLoggedInScreen',
  ACS: 'ACS',
  USER_ACCESS: 'User access',
  NEW_SERVICE: 'New services',
  MY_LOANS: 'My loans',
  LIMITS: 'Daily limits',
  DEMAT_PAN_UPDATE: 'dematPanUpdateModal',
  REFER_AND_EARN: 'referandearn',
  ENACH: 'enach',
  ENACH_CONFIRMATION: 'enachConfirmationScreen',
  FEEDBACK: 'feedback',
  SAFE_PAY: 'SafePay',
  TRANSACTION_DETAIL: 'TransactionDetail',
  VIRTUAL_ACCOUNTS: 'virtualAccountModal',
};
