export default {
  APPROVALS: 'Approvals',
  RECEIVED: 'Received',
  HISTORY: 'History',
  MIGRATION: 'MigrationScreen',
  MIGRATION_SUCCESS: 'MigrationSuccessScreen',
  BIB_MIGRATION_SUCCESS: 'BIBMigrationSuccessScreen',
  APPROVAL_DETAILS: 'ApprovalDetails',
  REJECT_COMMENT: 'RejectComment',
  ACCESS_MANAGEMENT: 'accessManagement',
  SERVICE_REQUEST: 'serviceRequest',
  LIMITS: 'Daily limits',
  USER_ACCESS: 'User access',
  CHEQUEBOOK_MANAGEMENT: 'chequeBookManagement',
  CHEQUEBOOK_LIST: 'EChequeBookList',
  CUSTOMER_PROFILE: 'profile',
  OFFERS: 'offers',
  SETTINGS: 'Settings',
  FAQS_AND_VIDEOS: 'FAQsAndVideos',
  UNIVERSAL_SEARCH_FAQS: 'UniversalSearchFAQs',
  NEW_FEATURES: 'NewFeatures',
  DEMO_VIDEOS: 'DemoVideos',
  DEMO_VIDEO_DETAILS: 'DemoVideoDetails',
  FAQ_DETAILS: 'FAQDetails',
  FAQ: 'FAQ',
  NEWS: 'News',
  UPDATE_TRANSFER_LIMIT: 'updateTransferLimit',
  UPDATE_DAILY_TRANSFER_SUCCESS: 'updateDailyTransferSuccess',
  CHANGE_MPIN: 'ChangeMpin',
  CHANGE_MPIN_SUCCESS: 'changeMpinSuccess',
  SERVICE_REQUEST_FILTER: 'ServiceRequestFilter',
  TRACK_SR_FILTER: 'TrackSRFilter',
  ACTIVATION_LINK_SENT: 'activationLinkSent',
  MORE: 'more',
  MANAGE_PROFILE: 'manageProfileForBIB',
  USER_LIST: 'UserList',
  ACCOUNTS_FILTER: 'AccountsFilter',
  APPROVAL_FILTERS: 'ApprovalFilters',
  GSTIN: 'GSTIN',
  USER_DETAILS: 'UserDetails',
  EDIT_PERSONAL_CUSTOMER_DETAILS_AUS: 'editPersonalCustomerDetailsForAUS',
  THEMES_SETTINGS: 'themesSettings',
  COVENANTS: 'Covenants',
  COVENANTS_DETAILS: 'CovenantsDetails',
  ASSISTANT_SCREEN: 'assistantScreen',
  VIRTUAL_ACCOUNTS: 'virtualAccount',
  VIRTUAL_ACCOUNTS_ACTIVE: 'Active',
};
